import type { Metadata } from "next";
import { LegalPage } from "@/app/terms/page";

export const metadata: Metadata = { title: "Partner Agreement", alternates: { canonical: "/partner-agreement" } };
const sections = [
  ["1. Application, approval, and activation", "Submitting an application does not approve or activate a partner and does not guarantee compensation. Approval allows BubsBookings to assign a personal affiliate code, but only activation authorizes new referral attribution. Participation begins when BubsBookings activates the partner after review. The code and dashboard access may not be sold, transferred, shared, or used to impersonate another person. BubsBookings may approve, reject, activate, pause, suspend, or terminate participation based on program fit, compliance, safety, fraud, legal, or payment risk."],
  ["2. Promotion and disclosures", "Partners must describe BubsBookings accurately and clearly disclose that they may earn compensation wherever a referral link or code is promoted. Partners may not make earnings guarantees, false endorsements, deceptive comparisons, unsupported safety claims, send spam, use unlawful content, bid on protected BubsBookings brand terms, impersonate BubsBookings, create confusing domains or accounts, or use cookies, redirects, toolbars, adware, or technical methods that create attribution without an informed user action."],
  ["3. Attribution", "The initial program uses the last valid active-partner referral before provider attribution. A valid manual code entered during provider onboarding intentionally replaces a saved referral cookie. A referral identifier is single-use, and attribution normally locks when a new provider profile is created so later clicks cannot change it. BubsBookings may correct a documented error through an audited administrative action. Attribution windows and other terms come from the program assigned to the partner and are snapshotted for the referred provider."],
  ["4. Qualified providers", "A signup alone does not earn an activation bonus. A qualified provider must be genuinely new, complete required onboarding, publish at least one legitimate active listing, complete an eligible paid booking, and pass applicable refund, dispute, chargeback, fraud, and holding-period checks. Duplicate accounts, self-referrals, related-party transactions created mainly to generate compensation, canceled or fabricated services, and other manipulated activity are ineligible."],
  ["5. Commission calculation", "Commission is calculated from eligible BubsBookings revenue defined by the program. Unless a program expressly says otherwise, eligible revenue is the actual provider marketplace fee snapshotted on the booking, adjusted for refunds. It is not the provider's gross service price and excludes the customer service fee, subscription revenue, taxes, tips, Stripe processing amounts, and other revenue types. Program rates, duration, eligible plans and revenue, activation bonus, hold period, and minimum payout may vary. The terms snapshotted at attribution govern unless both parties validly agree otherwise."],
  ["6. Holds, adjustments, and reversals", "Commission may remain pending or on hold while a booking, refund window, dispute, chargeback, fraud review, tax requirement, or payment issue is unresolved. BubsBookings may reject ineligible commission or create a visible reversal or negative adjustment after a refund, chargeback, duplicate, error, or prohibited activity. Financial ledger entries are retained rather than silently deleted."],
  ["7. Payouts and taxes", "Partners are responsible for accurate payee and tax information and all taxes on their compensation. Payable balances below the applicable minimum carry forward. The initial program uses administrator-reviewed manual payouts on the configured schedule; provider Stripe Connect payouts are separate and do not establish a partner payout account. A payout is complete when the recorded payment method reports it sent, subject to later correction or reversal where permitted."],
  ["8. Confidentiality and privacy", "The partner dashboard may show limited provider business names and referral progress. Partners must not attempt to identify customers, access private addresses or payment information, combine dashboard data with unauthorized sources, or disclose nonpublic program information. BubsBookings may use and retain partner application, attribution, commission, payout, tax, fraud-prevention, and audit information as described in the Privacy Policy."],
  ["9. Changes and termination", "BubsBookings may change future program terms, pause new referrals, or end a program with reasonable notice where practical. Existing provider referrals retain their stored program snapshot unless the agreement or law permits a change. After suspension or termination, new attribution and commission may stop; valid, non-disputed payable amounts remain subject to these terms, setoff rights, tax readiness, and applicable law."],
  ["10. General terms and contact", "The BubsBookings Terms of Service also apply and control general account, marketplace, disclaimer, liability, governing-law, and dispute provisions. This agreement does not create employment, agency, franchise, partnership, or authority to bind BubsBookings. Questions may be sent to christian@bubsbookings.com."],
] as const;
export default function PartnerAgreementPage(){return <LegalPage eyebrow="Legal" title="Partner Agreement" intro="The rules for promoting BubsBookings and earning compensation for qualified provider referrals." sections={sections}/>;}
