import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";
const read=(path:string)=>readFile(new URL(`../${path}`,import.meta.url),"utf8");
test("CRM derives tenant-scoped clients from real booking activity",async()=>{const route=await read("app/api/providers/clients/route.ts"),logic=await read("lib/provider-marketing.ts");assert.match(logic,/b\.provider_id::text=\$1/);assert.match(logic,/b\.provider_deleted_at IS NULL/);assert.match(route,/eligible\(access\.providerId,customerId\)/);assert.doesNotMatch(route,/SELECT \* FROM "user"/);});
test("notes and tags are private, provider scoped, and server authorized",async()=>{const route=await read("app/api/providers/clients/route.ts");assert.match(route,/getMarketingAccess\("clients"\)/);assert.match(route,/provider_client_notes\(provider_id,customer_id,author_user_id,body\)/);assert.match(route,/provider_id::text=\$1 AND customer_id=\$2 AND tag_id::text=\$3/);});
test("campaign recipients are snapshotted and suppression is rechecked per send",async()=>{const route=await read("app/api/providers/campaigns/route.ts"),job=await read("lib/marketing-jobs.ts");assert.match(route,/marketing_campaign_recipients\(campaign_id,provider_id,customer_id,email,display_name,personalization\)/);assert.match(job,/provider_marketing_preferences/);assert.match(job,/marketing_suppressions/);assert.match(job,/status='sending'/);assert.match(job,/campaign-\$\{row\.campaign_id\}-recipient-\$\{row\.id\}/);});
test("providers can inspect draft eligibility and saved campaign recipients",async()=>{const route=await read("app/api/providers/campaigns/route.ts"),manager=await read("components/provider-campaign-manager.tsx");assert.match(route,/action==="audience_preview"/);assert.match(route,/campaign\.status!=="draft"/);assert.match(route,/SELECT display_name,email,status FROM marketing_campaign_recipients/);assert.match(route,/recipients\.push\(\{displayName:/);assert.match(manager,/View recipients/);assert.match(manager,/Saved campaign audience/);assert.match(manager,/recipient\.email/);assert.match(manager,/recipient\.status\.replaceAll/);});
test("campaign delivery obeys an atomic daily allowance and automatically resumes",async()=>{const marketing=await read("lib/provider-marketing.ts"),job=await read("lib/marketing-jobs.ts"),scheduler=await read("instrumentation.ts"),migration=await read("database/migrations/077_marketing_email_daily_quota.sql"),manager=await read("components/provider-campaign-manager.tsx");assert.match(migration,/idempotency_key text NOT NULL UNIQUE/);assert.match(marketing,/MARKETING_DAILY_SEND_LIMIT\?\?75/);assert.match(marketing,/pg_advisory_xact_lock/);assert.match(marketing,/Daily marketing email allowance reached/);assert.match(job,/Automatically queued for tomorrow/);assert.match(job,/row_number\(\) OVER\(PARTITION BY r\.provider_id/);assert.match(scheduler,/runMarketingCampaignBatch/);assert.match(scheduler,/5 \* 60_000/);assert.match(manager,/Automatic free-plan queue/);});

test("providers can delete their own draft or cancelled campaigns while active and completed reporting remains protected",async()=>{const route=await read("app/api/providers/campaigns/route.ts"),manager=await read("components/provider-campaign-manager.tsx");assert.match(route,/\["draft","cancelled"\]\.includes\(campaign\.status\)/);assert.match(route,/provider_id::text=\$2 AND status IN\('draft','cancelled'\)/);assert.match(route,/marketing_campaign_deleted/);assert.match(manager,/\["draft","cancelled"\]\.includes\(c\.status\)/);assert.match(manager,/method:"DELETE"/);assert.match(manager,/Active and completed campaigns cannot be deleted/);assert.match(manager,/Delete campaign/);});
test("marketing prefers isolated credentials, safely falls back to deployed email settings, and supports standards-based unsubscribe",async()=>{const email=await read("lib/provider-marketing.ts"),unsubscribe=await read("app/api/marketing/unsubscribe/route.ts");assert.match(email,/RESEND_MARKETING_API_KEY\?\?process\.env\.RESEND_API_KEY/);assert.match(email,/MARKETING_EMAIL_FROM\?\?process\.env\.EMAIL_FROM/);assert.match(email,/bubsbookings-marketing-token-v1/);assert.match(email,/validMarketingEmail\(marketingEmailFrom\(\)\)/);assert.match(email,/List-Unsubscribe/);assert.match(email,/List-Unsubscribe-Post/);assert.match(unsubscribe,/signed|readMarketingToken/);assert.match(unsubscribe,/status='unsubscribed'/);});
test("bounce and complaint events create suppressions",async()=>{const webhook=await read("app/api/webhooks/marketing-email/route.ts");assert.match(webhook,/svix-signature/);assert.match(webhook,/email\.bounced/);assert.match(webhook,/email\.complained/);assert.match(webhook,/marketing_suppressions/);});
test("campaign clicks and bookings use opaque signed attribution",async()=>{const click=await read("app/api/marketing/click/route.ts"),booking=await read("app/api/bookings/route.ts");assert.match(click,/signedMarketingToken/);assert.match(click,/httpOnly:\s*true/);assert.match(booking,/readMarketingToken/);assert.match(booking,/campaignAttribution\.p === service\.provider_id/);assert.match(booking,/marketing_attributions/);});
test("ordinary team members receive no CRM or campaign permissions by default",async()=>{const migration=await read("database/migrations/076_provider_client_crm_and_campaigns.sql"),access=await read("lib/provider-marketing.ts");assert.match(migration,/can_view_clients boolean NOT NULL DEFAULT false/);assert.match(migration,/can_send_campaigns boolean NOT NULL DEFAULT false/);assert.match(access,/can_view_clients/);assert.match(access,/can_manage_campaigns/);assert.match(access,/can_send_campaigns/);});
test("async form submissions keep a stable form reference before resetting",async()=>{const files=await Promise.all(["components/provider-campaign-manager.tsx","components/affiliate-admin.tsx","components/provider-customer-tools.tsx","components/provider-profile-editor.tsx"].map(read));for(const source of files){assert.doesNotMatch(source,/event\.currentTarget\.reset\(\)/);assert.match(source,/formElement\s*=\s*event\.currentTarget/);}});
test("public policies describe campaign records and prohibit spam without internal labels",async()=>{const privacy=await read("app/privacy/page.tsx"),agreement=await read("app/provider-agreement/page.tsx");assert.match(privacy,/campaign audience snapshots/);assert.match(agreement,/purchase, scrape, rent/);assert.doesNotMatch(privacy,/NEEDS LEGAL REVIEW|INTERNAL NOTE|TODO/);assert.doesNotMatch(agreement,/NEEDS LEGAL REVIEW|INTERNAL NOTE|TODO/);});
