import type { Metadata } from "next";
import { LegalPage } from "@/app/terms/page";

export const metadata: Metadata = { title: "AI & Safety Transparency | BubsBookings" };

const sections = [
  ["1. What is automated", <><p>BubsBookings currently uses two in-house, rules-based systems that the product may call the Safety Bot. Content screening checks newly submitted messages, listing text, booking notes, cancellation reasons, and reviews for selected patterns associated with profanity, harassment, hate, explicit sexual or exploitative content, credible threats, and serious illegal transactions.</p><p className="mt-3">Provider onboarding separately checks whether an email is verified, whether a phone number has a plausible length, whether required business details are complete, whether a description has enough detail, and whether selected placeholder or suspicious payment language appears.</p></>],
  ["2. Inputs, outputs, and consequences", "The systems use only the submitted fields and account statuses described above. Content screening returns allow or block, a category, and a severity. Provider screening returns pass or request-changes, a score, and a checklist summary. A blocked submission is not posted; a provider profile that needs changes is not published through that submission. Neither system sets prices, accepts or denies bookings, ranks search results, decides disputes, or determines criminal risk."],
  ["3. Data records and outside AI", "For blocked content, BubsBookings stores the account, feature, category, severity, action, time, and a SHA-256 one-way fingerprint of the rejected text; it does not create a separate readable moderation copy of that rejected submission. Provider screening stores its status, score, summary, and check time. These systems run with BubsBookings code and do not send private messages, booking text, or listings to a third-party generative-AI model for moderation. No outside AI model is being represented as the author of these rules."],
  ["4. Important limits", "Rules can miss harmful content, misunderstand reclaimed words, slang, quotations, spelling, or context, and can be evaded. A pass does not verify identity, licenses, insurance, credentials, service quality, or criminal history and is not a BubsBookings endorsement. A block does not prove misconduct. Users must still use judgment, review provider information, keep communication on-platform, and report concerns."],
  ["5. Human review and appeals", "Administrators can review reports, disputes, listings, booking and payment records, and limited moderation-event information. A user who believes content or a provider profile was incorrectly blocked can contact support with the affected feature and approximate time. BubsBookings may correct an error, explain a relevant rule, request revised content, or uphold the action. Material account or payout enforcement should consider the available context rather than relying only on an automated match."],
  ["6. Fairness and changes", "The same content rules apply to customers and providers and are not designed to use race, color, religion, national origin, sex, disability, age, or other protected traits to rank or approve people. Because language rules can affect groups differently, reports of repeated false positives should be reviewed. Material changes to the purpose, data, or consequences of these systems will be reflected on this page and, where required, presented for new consent."],
  ["7. Safety and emergencies", "The Safety Bot is not monitored emergency response. If someone may be in immediate danger, call 911 or the appropriate local emergency service. Stop communicating with anyone who pressures you to leave the platform, send gift cards or cryptocurrency, reveal authentication codes, or provide unnecessary financial, identity, or health information. Use BubsBookings reporting and account-security tools for non-emergency concerns."],
] as const;

export default function AiTransparencyPage() {
  return <LegalPage eyebrow="Trust and safety" title="Automation & AI transparency" intro="What BubsBookings’s Safety Bot does, what data it uses, and where automated judgment stops." sections={sections} />;
}
