import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage } from "@/app/terms/page";

export const metadata: Metadata = { title: "Privacy Policy" };

const sections = [
  ["1. Scope and information collected", <><p>This policy applies to the BubsBookings website, accounts, marketplace, and support tools. We collect information you provide: name, email, phone, authentication data such as password hashes, profile photo, service and business details, photos, availability, location and working radius, booking address and notes, quotes, messages, reviews, team information, reports, disputes, support requests, preferences, and agreement records.</p><p className="mt-3">We also collect transaction and status information from Stripe; Google profile information when you choose Google sign-in; and technical data such as IP address, browser, device, pages and features used, timestamps, session identifiers, security events, analytics identifiers, and approximate location based on the area you select. If you allow browser location access, your device provides coordinates temporarily to the page to choose a nearby supported city; BubsBookings does not send or store those precise coordinates as part of that feature. Your browser or operating system controls the permission.</p></>],
  ["2. Sources and purposes", "Information comes from you, the other participant in a booking, service providers acting for us, and activity on BubsBookings. We use it to create and secure accounts; authenticate users; publish and search listings; calculate distance; manage availability, bookings, quotes, payments, refunds, transfers, messages, notifications, reviews, and support; enforce plans; detect abuse; investigate reports and disputes; maintain legal and financial records; measure reliability and conversion; and improve the service. First-party analytics may record searches, page and listing views, booking and checkout events, cancellations, refunds, and related identifiers."],
  ["3. Information visible to other users", "Public listings may show provider or business names, profile and listing photos, general service area, working radius, pricing, availability, descriptions, and reviews. Booking participants receive the names, messages, booking details, and contact or address information reasonably needed for the service. A message thread is associated with its service or booking participants. Do not submit passwords, authentication codes, full card numbers, government identifiers, or information another person has not authorized you to share."],
  ["4. Payments and identity verification", <>Stripe collects and processes payment-card, billing, subscription, connected-account, bank-payout, tax, fraud, and identity-verification data under <a href="https://stripe.com/privacy" target="_blank" rel="noreferrer" className="font-bold underline">Stripe&apos;s Privacy Policy</a>. BubsBookings receives identifiers and statuses needed to operate payments, but does not receive or store full card numbers or bank-login credentials. Because marketplace charges are created on the BubsBookings Stripe platform account, BubsBookings may receive and use transaction, refund, chargeback, risk, and connected-account information to administer the payment flow.</>],
  ["5. Automated safety and provider screening", <><p>Submitted text in messages, listings, reviews, cancellation reasons, and booking notes is checked by BubsBookings-operated pattern rules. A blocked attempt creates a record with the account, feature, category, severity, time, and a one-way content fingerprint, not an additional readable copy of the rejected text.</p><p className="mt-3">Provider checks also use email-verification and agreement status, matching phone-number format, profile and listing completeness, location and pricing fields, and selected suspicious-language patterns. Stripe supplies connected-account identity and payout-readiness status. BubsBookings stores check results, score, time, and provider account. A phone-format match is not SMS ownership verification; a business-profile pass is not license, registration, insurance, or criminal-background verification. Marketplace text is not sent to a third-party generative-AI provider for these checks.</p></>],
  ["6. Disclosure and service providers", "We disclose information as needed to Stripe; Google for optional sign-in and website analytics; hosting, database, file-storage, email-delivery, security, and operational vendors; booking participants; professional advisers; and authorities or others when required by law or reasonably necessary to protect rights, safety, payments, or the service. Information may also transfer as part of a merger, financing, acquisition, or sale, subject to appropriate notice and protection. We do not sell personal information or share it for cross-context behavioral advertising, and we do not use third-party targeted-advertising trackers."],
  ["7. Cookies, sessions, and choices", <>BubsBookings uses cookies or similar browser storage for sign-in sessions, security, preferences, necessary product functions, first-party product analytics, and Google Analytics measurement of website traffic and feature use. Google explains <a href="https://policies.google.com/technologies/partner-sites" target="_blank" rel="noreferrer" className="font-bold underline">how it uses information from sites that use its services</a>. Blocking necessary cookies can prevent account features from working. Browser privacy controls or content blockers may limit analytics. Read the <Link href="/cookies" className="font-bold underline">Cookie Notice</Link> for the technologies and controls currently used. You can update common profile, listing, availability, notification, security, and location settings in your account. Transactional and legal messages are part of the service; optional marketing communications, if introduced, will provide the choices required by law.</>],
  ["8. Retention and deletion", <><p>We retain account and marketplace information while an account is active and as needed to provide the service. Retention after that depends on the record: transaction, tax, consent, dispute, fraud-prevention, security, and legal records may be kept for the time reasonably needed to meet those purposes or a legal requirement; operational logs and support records are kept only while useful for security, support, or accountability; and backup copies are removed through the ordinary backup-overwrite cycle. We delete or deidentify information when the applicable purpose ends unless law permits or requires longer retention.</p><p className="mt-3">You can permanently delete your account from Account Settings. Deletion removes the account and associated BubsBookings profile, listings, uploaded images, availability, team records, bookings, messages, reviews, favorites, notifications, support requests, and linked marketplace records. Active bookings, unresolved disputes, or unsettled payments must be resolved first so deletion does not interrupt another user&apos;s service or money.</p><p className="mt-3">BubsBookings also attempts to cancel linked subscriptions and delete connected Stripe customer or provider-account records. Stripe, banks, card networks, tax authorities, and fraud-prevention systems apply their own legal and operational retention rules. Any limited records BubsBookings retains after account deletion are restricted from ordinary product use.</p></>],
  ["9. Security, incidents, and international processing", "We use reasonable administrative, technical, and organizational safeguards appropriate to the information and service, including authenticated access and encrypted network connections. No system is perfectly secure. Use a unique password, enable two-factor authentication when available, and promptly report suspicious activity. We investigate suspected data incidents and notify affected people and regulators when applicable law requires it. BubsBookings and its providers may process information in the United States and other locations where they operate, subject to applicable protections."],
  ["10. Privacy rights and data downloads", <><p>You can download a portable JSON copy of data connected to your account or permanently delete the account from <Link href="/account/settings" className="font-bold underline">Account Settings</Link>. Download your copy before deleting because deletion cannot be undone. Passwords, authentication secrets, full payment-card data, and bank credentials are not included in the download.</p><p className="mt-3">Depending on where you live, you may also have rights to know, access, correct, delete, or obtain a copy of personal information; withdraw certain consent; opt out of certain processing; appeal a denied request; and receive non-discriminatory service for exercising a right. Submit requests that cannot be completed with the self-service controls through Contact Support or email <a href="mailto:christian@bubsbookings.com" className="font-bold underline">christian@bubsbookings.com</a>. No account is required to email a request. We may verify identity or an authorized agent&apos;s authority, deny or limit a request where permitted, and retain limited information where legally required or necessary to protect rights, payments, and security. We will respond within the period required by applicable law and explain any available appeal process.</p></>],
  ["11. Health and other sensitive information", <>BubsBookings is not a medical or health-care service and does not intentionally request or use consumer health data, diagnoses, medical records, biometric identifiers, Social Security numbers, or government IDs in marketplace text. Do not use BubsBookings to offer or obtain medical or health-care services, and do not put health information or other unnecessary sensitive information in a listing, message, review, booking note, photo, or support request. If sensitive information is submitted incidentally, BubsBookings may restrict or delete it when identified. BubsBookings does not use booking activity to infer health conditions for advertising and does not sell consumer health data. Questions or deletion requests concerning possible health information may be emailed to <a href="mailto:christian@bubsbookings.com" className="font-bold underline">christian@bubsbookings.com</a>.</>],
  ["12. Children", "BubsBookings is for adults age 18 or older and is not directed to children. We do not knowingly allow a child to create an account or book or provide a service. If you believe a child submitted personal information, contact support so it can be investigated and deleted as appropriate. Family-friendly content standards do not make the service child-directed."],
  ["13. Changes and contact", <>We may update this policy as the service, vendors, or law changes. We will post the updated effective date and give additional notice or obtain consent when required. Submit privacy questions, requests, complaints, or appeals through Contact Support or email <a href="mailto:christian@bubsbookings.com" className="font-bold underline">christian@bubsbookings.com</a>. You may also contact the privacy regulator or attorney general available in your jurisdiction.</>],
] as const;

export default function PrivacyPage() {
  return <LegalPage eyebrow="Your information" title="Privacy Policy" intro="A plain-language explanation of what BubsBookings collects, why we use it, and how automated safety checks work." sections={sections} />;
}
