import type { Metadata } from "next";
import { LegalPage } from "@/app/terms/page";

export const metadata: Metadata = { title: "Privacy Policy | BubsBookings" };

const sections = [
  ["1. Scope and information collected", <><p>This policy applies to the BubsBookings website, accounts, marketplace, and support tools. We collect information you provide: name, email, phone, encrypted account credentials, profile photo, service and business details, photos, availability, location and working radius, booking address and notes, quotes, messages, reviews, team information, reports, disputes, support requests, preferences, and agreement records.</p><p className="mt-3">We also collect transaction and status information from Stripe; Google profile information when you choose Google sign-in; and technical data such as IP address, browser, device, pages and features used, timestamps, session identifiers, security events, and approximate location inferred from the area you choose. We do not intentionally collect precise background GPS location.</p></>],
  ["2. Sources and purposes", "Information comes from you, the other participant in a booking, service providers acting for us, and activity on BubsBookings. We use it to create and secure accounts; authenticate users; publish and search listings; calculate distance; manage availability, bookings, quotes, payments, refunds, transfers, messages, notifications, reviews, and support; enforce plans; detect abuse; investigate reports and disputes; maintain legal and financial records; measure reliability and conversion; and improve the service. First-party analytics may record searches, page and listing views, booking and checkout events, cancellations, refunds, and related identifiers."],
  ["3. Information visible to other users", "Public listings may show provider or business names, profile and listing photos, general service area, working radius, pricing, availability, descriptions, and reviews. Booking participants receive the names, messages, booking details, and contact or address information reasonably needed for the service. A message thread is associated with its service or booking participants. Do not submit passwords, authentication codes, full card numbers, government identifiers, or information another person has not authorized you to share."],
  ["4. Payments and identity verification", <>Stripe collects and processes payment-card, billing, subscription, connected-account, bank-payout, tax, fraud, and identity-verification data under <a href="https://stripe.com/privacy" target="_blank" rel="noreferrer" className="font-bold underline">Stripe&apos;s Privacy Policy</a>. BubsBookings receives identifiers and statuses needed to operate payments, but does not receive or store full card numbers or bank-login credentials. Because marketplace charges are created on the BubsBookings Stripe platform account, BubsBookings may receive and use transaction, refund, chargeback, risk, and connected-account information to administer the payment flow.</>],
  ["5. Automated safety and provider screening", <><p>Submitted text in messages, listings, reviews, cancellation reasons, and booking notes is checked by BubsBookings-operated pattern rules. A blocked attempt creates a record with the account, feature, category, severity, time, and a one-way content fingerprint, not an additional readable copy of the rejected text.</p><p className="mt-3">Provider onboarding also automatically checks email-verification status, phone-number format, profile completeness, description length, and selected suspicious-language patterns. The checks can allow publication or request changes. They are not identity, license, insurance, or criminal-background verification. Marketplace text is not sent to a third-party generative-AI provider for these checks.</p></>],
  ["6. Disclosure and service providers", "We disclose information as needed to Stripe; Google sign-in; hosting, database, file-storage, email-delivery, security, and operational vendors; booking participants; professional advisers; and authorities or others when required by law or reasonably necessary to protect rights, safety, payments, or the service. Information may also transfer as part of a merger, financing, acquisition, or sale, subject to appropriate notice and protection. We do not sell personal information or share it for cross-context behavioral advertising, and we do not use third-party targeted-advertising trackers."],
  ["7. Cookies, sessions, and choices", "BubsBookings uses cookies or similar browser storage for sign-in sessions, security, preferences, and necessary product functions. Blocking necessary cookies can prevent account features from working. You can update common profile, listing, availability, notification, security, and location settings in your account. Transactional and legal messages are part of the service; optional marketing communications, if introduced, will provide the choices required by law."],
  ["8. Retention and deletion", "We retain account and marketplace information while an account is active and then for as long as reasonably necessary for bookings, payments, taxes, fraud prevention, safety, disputes, enforcement, backups, and legal obligations. Retention varies by record and applicable law. Deleting a photo, message, conversation, notification, listing, or account-facing item may remove it from normal display without immediately deleting transaction, moderation, backup, or legally required records. When no longer needed, information is deleted, deidentified, or securely isolated according to our retention practices."],
  ["9. Security and international processing", "We use reasonable administrative, technical, and organizational safeguards appropriate to the information and service, including authenticated access and encrypted network connections. No system is perfectly secure. Use a unique password, enable two-factor authentication when available, and promptly report suspicious activity. BubsBookings and its providers may process information in the United States and other locations where they operate, subject to applicable protections."],
  ["10. Privacy rights", "Depending on where you live, you may have rights to know, access, correct, delete, or obtain a copy of personal information; withdraw certain consent; opt out of certain processing; appeal a denied request; and receive non-discriminatory service for exercising a right. Submit a request through Contact Support. We may verify your identity, ask an authorized agent for proof of authority, deny or limit a request where permitted, and retain information where legally required or necessary to protect rights and security."],
  ["11. Health and other sensitive information", "BubsBookings is not a medical service and does not ask users to provide diagnoses, medical records, biometric identifiers, Social Security numbers, or government IDs in marketplace text. Do not include health information unless it is strictly necessary for a service and you are authorized to share it. BubsBookings does not use booking activity to infer health conditions for advertising and does not sell consumer health data. If BubsBookings later intentionally collects consumer health data, it will provide any separate notice and consent required by applicable law before doing so."],
  ["12. Children", "BubsBookings is for adults age 18 or older and is not directed to children. We do not knowingly allow a child to create an account or book or provide a service. If you believe a child submitted personal information, contact support so it can be investigated and deleted as appropriate. Family-friendly content standards do not make the service child-directed."],
  ["13. Changes and contact", "We may update this policy as the service, vendors, or law changes. We will post the updated effective date and give additional notice or obtain consent when required. Submit privacy questions, requests, or complaints through Contact Support in BubsBookings. If a request is denied, reply through support and ask for an appeal. You may also contact the privacy regulator or attorney general available in your jurisdiction."],
] as const;

export default function PrivacyPage() {
  return <LegalPage eyebrow="Your information" title="Privacy Policy" intro="A plain-language explanation of what BubsBookings collects, why we use it, and how automated safety checks work." sections={sections} />;
}
