"use client";

import Link from "next/link";
import { useCallback,useEffect,useState } from "react";
type Item={id:string;displayName:string;relationship:string;body:string;status:string;createdAt:string;providerName:string;providerSlug:string};

export default function AdminRecommendationManager(){
  const [items,setItems]=useState<Item[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState("");const [error,setError]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/admin/recommendations",{cache:"no-store"}).catch(()=>null);if(response?.ok){const data=await response.json() as {recommendations:Item[]};setItems(data.recommendations);}else setError("Recommendations could not be loaded.");setLoading(false);},[]);
  useEffect(()=>{const controller=new AbortController();fetch("/api/admin/recommendations",{cache:"no-store",signal:controller.signal}).then(async response=>response.ok?response.json() as Promise<{recommendations:Item[]}>:null).then(data=>{if(data)setItems(data.recommendations);else setError("Recommendations could not be loaded.");}).catch(()=>null).finally(()=>setLoading(false));return()=>controller.abort();},[]);
  async function update(id:string,status:string){setBusy(id);setError("");const response=await fetch("/api/admin/recommendations",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status})}).catch(()=>null);if(!response?.ok){const data=response?await response.json() as {error?:string}:null;setError(data?.error??"That change could not be saved.");setBusy("");return;}await load();setBusy("");}
  if(loading)return <p className="mt-8 text-sm text-[#718078]">Loading recommendations…</p>;
  return <section className="mt-7 grid gap-4">{error&&<p role="alert" className="rounded-xl bg-[#fff0e7] p-4 text-sm font-bold text-[#9a4e25]">{error}</p>}{items.map(item=><article key={item.id} className="rounded-[1.7rem] border border-[#183126]/10 bg-white p-5 sm:p-6"><div className="flex flex-col justify-between gap-4 sm:flex-row"><div><span className="rounded-full bg-[#edf2e9] px-3 py-1 text-[10px] font-bold uppercase">{item.status}</span><h2 className="mt-3 text-lg font-bold">{item.displayName} for {item.providerName}</h2><p className="mt-1 text-xs text-[#718078]">{item.relationship} · {new Date(item.createdAt).toLocaleString()}</p><p className="mt-4 max-w-3xl whitespace-pre-wrap text-sm leading-6 text-[#52665b]">{item.body}</p></div><div className="flex shrink-0 flex-wrap gap-2 sm:flex-col"><Link href={`/providers/${item.providerSlug}`} target="_blank" className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold text-center">View provider</Link><button disabled={busy===item.id} onClick={()=>void update(item.id,"approved")} className="rounded-full bg-[#183126] px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Approve</button><button disabled={busy===item.id} onClick={()=>void update(item.id,"hidden")} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold disabled:opacity-50">Hide</button><button disabled={busy===item.id} onClick={()=>void update(item.id,"rejected")} className="rounded-full px-4 py-2 text-xs font-bold text-[#9a4e25] disabled:opacity-50">Reject</button></div></div></article>)}</section>;
}
