"use client";

import { FormEvent, useCallback, useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import UiIcon from "@/components/ui-icon";
import CustomSelect from "@/components/custom-select";
import DatePicker from "@/components/date-picker";

type Data = {
  summary: Record<string, number>;
  reserve: { obligationCents: number; payableCents: number; safetyBufferCents: number; requiredCents: number; availableCents: number | null; shortfallCents: number | null; protectedOwnerPayoutsEnabled: boolean };
  programs: Array<Record<string, string | number | boolean | string[] | number[] | null>>;
  affiliates: Array<Record<string, string | number | boolean | string[] | number[] | null>>;
  commissions: Array<Record<string, string | number | null>>;
  payouts: Array<Record<string, string | number | null>>;
  campaigns: Array<Record<string, string | number | null>>;
  recentClicks: Array<Record<string, string | null>>;
  auditHistory: Array<Record<string, string | null>>;
  milestoneAchievements: Array<Record<string, string | number | null>>;
};
type AffiliateItem = Record<string, string | number | boolean | string[] | number[] | null>;
type PartnerDialog = { kind: "approve" | "readiness" | "adjustment" | "terms" | "historical"; item: AffiliateItem; approvalMode?: "standard" | "custom" };
type ProgramItem = Record<string, string | number | boolean | string[] | number[] | null>;
type ConfirmDialog = { kind: "commission" | "reversal"; item: AffiliateItem; status?: string };
const money = (value: unknown) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value ?? 0) / 100);
const label = (value: unknown) => String(value ?? "").replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
const suggestedCode = (value: unknown) => String(value ?? "PARTNER").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 20);
const audienceSize = (value: unknown) => {
  const parsed = Number(String(value ?? "").replaceAll(",", ""));
  return Number.isFinite(parsed) && parsed > 0 ? parsed.toLocaleString("en-US") : "";
};
const listValue = (value: unknown) => Array.isArray(value) && value.length ? value.join(", ") : "Not supplied";

export default function AffiliateAdmin() {
  const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState("");
  const [dialog,setDialog]=useState<PartnerDialog|null>(null);
  const [programDialog,setProgramDialog]=useState<ProgramItem|null>(null);
  const [confirmDialog,setConfirmDialog]=useState<ConfirmDialog|null>(null);
  const [copiedCode,setCopiedCode]=useState("");
  const load=useCallback(async()=>{const response=await fetch("/api/admin/affiliates",{cache:"no-store"}); if(!response.ok){setError("Partner data could not be loaded.");return;} setData(await response.json());setError("");},[]);
  useEffect(()=>{let active=true;fetch("/api/admin/affiliates",{cache:"no-store"}).then(async response=>response.ok?response.json() as Promise<Data>:null).catch(()=>null).then(result=>{if(!active)return;if(result)setData(result);else setError("Partner data could not be loaded.");});return()=>{active=false;};},[]);
  useEffect(()=>{if(!dialog&&!programDialog&&!confirmDialog)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous;};},[dialog,programDialog,confirmDialog]);
  async function action(body: Record<string,unknown>){setBusy(String(body.targetId??body.action));setError("");setNotice("");try{const response=await fetch("/api/admin/affiliates",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error??"Action failed.");return false;}setNotice("Partner records updated.");await load();return true;}catch{setError("The partner update could not be sent. Please try again.");return false;}finally{setBusy("");}}
  async function submitPartnerDialog(event: FormEvent<HTMLFormElement>){
    event.preventDefault();
    if(!dialog)return;
    const values=Object.fromEntries(new FormData(event.currentTarget));
    const form=new FormData(event.currentTarget);
    const compensation={compensationConfigured:true,compensationType:values.compensationType,
      activationBonusEnabled:form.has("activationBonusEnabled"),milestoneBonusesEnabled:form.has("milestoneBonusesEnabled"),
      revenueShareEnabled:form.has("revenueShareEnabled"),customCampaignEnabled:form.has("customCampaignEnabled"),
      activationBonus:values.activationBonus,revenueSharePercent:values.revenueSharePercent,durationMonths:values.durationMonths,
      minimumPayout:values.minimumPayout,customCampaignAmount:values.customCampaignAmount,
      customCampaignStartsOn:values.customCampaignStartsOn,customCampaignEndsOn:values.customCampaignEndsOn,
      customCampaignNotes:values.customCampaignNotes};
    let body:Record<string,unknown>={targetId:dialog.item.id};
    if(dialog.kind==="approve")body=dialog.approvalMode==="custom"
      ? {...body,action:"affiliate_status",status:"approved",code:values.code,programId:values.programId,...compensation,compensationType:"custom"}
      : {...body,action:"affiliate_status",status:"approved",code:values.code,programId:values.programId,compensationConfigured:false};
    if(dialog.kind==="readiness")body={...body,action:"affiliate_payment_readiness",ready:dialog.item.tax_onboarding_status!=="complete",reason:values.reason};
    if(dialog.kind==="adjustment")body={...body,action:"manual_adjustment",amount:values.amount,reason:values.reason};
    if(dialog.kind==="terms")body={...body,action:"affiliate_overrides",...compensation};
    if(dialog.kind==="historical")body={...body,action:"milestone_backfill_approve",reason:values.reason};
    if(await action(body))setDialog(null);
  }
  async function submitConfirmDialog(event: FormEvent<HTMLFormElement>){event.preventDefault();if(!confirmDialog)return;const values=Object.fromEntries(new FormData(event.currentTarget));let body:Record<string,unknown>={targetId:confirmDialog.item.id};if(confirmDialog.kind==="commission")body={...body,action:"commission_status",status:confirmDialog.status,reason:values.reason};if(confirmDialog.kind==="reversal")body={...body,action:"commission_reversal",reason:values.reason};if(await action(body))setConfirmDialog(null);}
  async function createProgram(event: FormEvent<HTMLFormElement>){
    event.preventDefault();
    const formElement=event.currentTarget;
    const form=new FormData(formElement);
    setBusy("program");setError("");setNotice("");
    try{
      const response=await fetch("/api/admin/affiliates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"program_create",...Object.fromEntries(form),milestoneBonusesEnabled:form.has("milestoneBonusesEnabled")})});
      const result=await response.json() as {error?:string};
      if(!response.ok){setError(result.error??"Program could not be created.");return;}
      formElement.reset();setNotice("Draft program created.");await load();
    }catch{setError("The program could not be saved. Please try again.");}finally{setBusy("");}
  }
  async function updateProgram(event: FormEvent<HTMLFormElement>){
    event.preventDefault();if(!programDialog)return;
    const form=new FormData(event.currentTarget); const values:Record<string,unknown>=Object.fromEntries(form);
    if(await action({action:"program_update",targetId:programDialog.id,...values}))setProgramDialog(null);
  }
  async function createCampaign(event: FormEvent<HTMLFormElement>){event.preventDefault();const formElement=event.currentTarget;const form=new FormData(formElement);setBusy("campaign");setError("");setNotice("");try{const response=await fetch("/api/admin/affiliates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"campaign_create",...Object.fromEntries(form)})});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error??"Campaign record could not be created.");return;}formElement.reset();setNotice("Creator campaign recorded. No payment was sent.");await load();}catch{setError("The campaign record could not be saved.");}finally{setBusy("");}}
  async function copyAffiliateCode(code: string){try{await navigator.clipboard.writeText(code);setCopiedCode(code);setNotice(`Affiliate code ${code} copied.`);}catch{setError("The affiliate code could not be copied. Select it manually and try again.");}}
  if(!data)return <div className="dashboard-container px-5 py-12">{error||"Loading partner operations…"}</div>;
  const metrics=[["Applications",data.summary.applications],["Active partners",data.summary.active_affiliates],["Provider referrals",data.summary.provider_referrals],["Qualified providers",data.summary.qualified_providers],["Affiliate obligations",money(data.reserve.obligationCents)],["Payable now",money(data.reserve.payableCents)],["Paid",money(data.summary.paid_cents)]];
  return <div className="dashboard-container px-5 py-10"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#687970]">Marketplace growth</p><h1 className="mt-2 text-4xl font-bold">Partners &amp; affiliates</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#687970]">Review applications, manage configurable programs, inspect referrals, approve ledger entries, and send audited payouts through Stripe Connect.</p></div>
    {(error||notice)&&<p role="status" className={`mt-5 rounded-2xl p-4 text-sm font-bold ${error?"bg-[#fff0e7] text-[#9a4e25]":"bg-[#e5f1e5] text-[#34704a]"}`}>{error||notice}</p>}
    <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{metrics.map(([name,value])=><article key={name} className="rounded-2xl bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[#718078]">{name}</p><p className="mt-2 text-xl font-bold">{value}</p></article>)}</section>
    <section className={`mt-4 rounded-[1.5rem] border p-5 ${Number(data.reserve.shortfallCents??0)>0?"border-[#b45f35]/30 bg-[#fff0e7]":"border-[#183126]/10 bg-[#e7f2e5]"}`} aria-labelledby="affiliate-reserve-heading"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#687970]">Stripe funding safeguard</p><h2 id="affiliate-reserve-heading" className="mt-1 text-xl font-bold">{data.reserve.availableCents===null?"Stripe balance unavailable":Number(data.reserve.shortfallCents??0)>0?"Affiliate reserve needs funding":"Affiliate obligations are covered"}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#5f7067]">BubsBookings tracks all unpaid affiliate earnings as an obligation and sends eligible affiliate payouts first. When protected owner payouts are enabled, Friday&apos;s owner payout sends only the Stripe surplus above this reserve.</p><p className={`mt-3 text-sm font-bold ${data.reserve.protectedOwnerPayoutsEnabled?"text-[#34704a]":"text-[#9a4e25]"}`}>{data.reserve.protectedOwnerPayoutsEnabled?"Protected owner payouts are enabled.":"Protected owner payouts are not enabled yet. Keep Stripe automatic payouts off before enabling them."}</p></div><div className="grid min-w-[15rem] grid-cols-2 gap-2 text-sm"><span>Required reserve</span><strong className="text-right">{money(data.reserve.requiredCents)}</strong><span>Stripe available</span><strong className="text-right">{data.reserve.availableCents===null?"Unavailable":money(data.reserve.availableCents)}</strong>{Number(data.reserve.shortfallCents??0)>0?<><span className="text-[#9a4e25]">Funding gap</span><strong className="text-right text-[#9a4e25]">{money(data.reserve.shortfallCents)}</strong></>:null}</div></div></section>
    <section className="mt-8 rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Applications and partners</h2><div className="mt-5 grid gap-4">{data.affiliates.map(item=><article key={String(item.id)} className="rounded-2xl border border-[#183126]/10 bg-[#f8f8f4] p-4">
      <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-bold">{item.display_name}</h3><p className="break-words text-sm text-[#687970]">{item.email} · {item.program_name}</p><p className="mt-1 text-xs leading-5 text-[#687970]">{item.clicks} clicks · {item.referrals} referrals · {item.qualified} qualified · {item.bookings_generated} bookings · {money(item.eligible_revenue_cents)} eligible revenue · {money(item.pending_cents)} pending · {money(item.payable_cents)} payable · {money(item.paid_cents)} paid</p></div><span className="rounded-full bg-[#edf3e7] px-3 py-1 text-xs font-bold">{["approved","active"].includes(String(item.status))?`${label(item.status)} · ${label(item.compensation_type)}`:label(item.status)}</span></div>
      <section aria-label="Linked BubsBookings account" className={`mt-4 rounded-2xl border p-4 ${item.user_id?"border-[#34704a]/20 bg-[#edf6ed]":"border-[#b45f35]/25 bg-[#fff0e7]"}`}>
        <div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-[#5f7067]">BubsBookings account</p>{item.user_id?<><p className="mt-2 text-sm font-bold">{item.account_name||item.display_name}</p><p className="break-all text-xs leading-5 text-[#5f7067]">{item.account_email} · User ID {item.user_id}</p></>:<><p className="mt-2 text-sm font-bold text-[#8b4526]">Account setup required</p><p className="mt-1 text-xs leading-5 text-[#765c4e]">Approval is blocked until this application is safely linked to one verified BubsBookings account.</p></>}</div><span className="rounded-full bg-white px-3 py-1 text-xs font-bold">{item.user_id?`${item.account_email_verified===true?"Email verified":"Email not verified"} · ${label(item.account_status)}`:label(item.account_link_status)}</span></div>
        {!item.user_id&&<div className="mt-3"><p className="text-xs leading-5 text-[#765c4e]">Exact account matches: {Number(item.matching_account_count??0)} · verified matches: {Number(item.matching_verified_account_count??0)}{item.account_link_review_note?` · ${item.account_link_review_note}`:""}</p>{Number(item.matching_verified_account_count)===1&&Number(item.matching_account_count)===1?<button type="button" disabled={busy===item.id} onClick={()=>void action({action:"affiliate_link_account",targetId:item.id})} className="mt-3 min-h-11 rounded-full border border-[#183126]/15 bg-white px-4 py-2 text-xs font-bold disabled:opacity-60">Link verified account</button>:<p className="mt-2 text-xs font-bold text-[#8b4526]">A unique verified-email match was not found. Review the account manually before linking.</p>}</div>}
      </section>
      {item.custom_partnership_requested===true&&<section aria-label="Custom partnership request" className="mt-4 rounded-2xl border border-[#a17c16]/25 bg-[#fff8d8] p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-[#765b12]">Custom Partnership Requested</p><div className="mt-3 grid gap-2 text-sm leading-6 sm:grid-cols-2"><p><strong>Partnership interests:</strong><br/>{listValue(item.custom_partnership_types)}</p><p><strong>Platforms:</strong><br/>{listValue(item.active_platforms)}</p><p><strong>Promotion options:</strong><br/>{listValue(item.promotion_types)}</p><p><strong>Audience sizes:</strong><br/>Followers {audienceSize(item.follower_count)||"—"} · Subscribers {audienceSize(item.subscriber_count)||"—"} · Email {audienceSize(item.email_list_size)||"—"} · Monthly traffic {audienceSize(item.monthly_website_traffic)||"—"} · Avg. views {audienceSize(item.average_content_views)||"—"}</p></div>{item.other_audience_size?<p className="mt-2 text-sm"><strong>Other audience:</strong> {item.other_audience_size}</p>:null}{item.custom_partnership_notes?<p className="mt-2 whitespace-pre-wrap text-sm leading-6"><strong>Partnership notes:</strong> {item.custom_partnership_notes}</p>:null}</section>}
      <p className="mt-3 whitespace-pre-wrap text-sm leading-6"><strong>Audience:</strong> {item.primary_audience||"Not supplied"}{audienceSize(item.audience_size)?` (${audienceSize(item.audience_size)})`:""}<br/><strong>Plan:</strong> {item.promotion_plan||"Not supplied"}<br/><strong>Stripe payouts:</strong> {item.stripe_account_id?(item.stripe_payouts_enabled?"Ready":Number(item.stripe_requirements_count)>0?`${item.stripe_requirements_count} requirements due`:"In review"):"Not connected"} · <strong>Tax review:</strong> {label(item.tax_onboarding_status)}{item.admin_notes?<><br/><strong>Admin notes:</strong> {item.admin_notes}</>:null}</p>
      <div className="mt-3 flex flex-wrap gap-x-4 gap-y-2 text-sm">{[["Website",item.website_url],["YouTube",item.youtube_url],["Instagram",item.instagram_url],["TikTok",item.tiktok_url],["X",item.x_url],["Facebook",item.facebook_url],["Other",item.other_social_url],["Media kit",item.media_kit_url],["Portfolio",item.portfolio_url]].filter((entry)=>entry[1]).map(([name,url])=><a key={String(name)} href={String(url)} target="_blank" rel="noreferrer" className="font-bold underline">{name}</a>)}</div><div className="mt-4 flex flex-wrap gap-2">
      {!["approved","active"].includes(String(item.status))&&<><button disabled={busy===item.id||!item.user_id} title={!item.user_id?"Link a verified BubsBookings account before approval":undefined} onClick={()=>setDialog({kind:"approve",item,approvalMode:"standard"})} className="rounded-full bg-[#eee25a] px-4 py-2 text-xs font-bold disabled:cursor-not-allowed disabled:opacity-45">Approve as Standard</button>{item.custom_partnership_requested===true&&<button disabled={busy===item.id||!item.user_id} title={!item.user_id?"Link a verified BubsBookings account before approval":undefined} onClick={()=>setDialog({kind:"approve",item,approvalMode:"custom"})} className="rounded-full bg-[#183126] px-4 py-2 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-45">Approve as Custom</button>}</>}
      {["applied","under_review"].includes(String(item.status))&&<button disabled={busy===item.id} onClick={()=>void action({action:"affiliate_status",targetId:item.id,status:"rejected",reason:"Application rejected by administrator"})} className="rounded-full border border-[#9a4e25]/25 bg-white px-4 py-2 text-xs font-bold text-[#9a4e25]">Reject</button>}
      {item.status==="approved"&&<button disabled={busy===item.id||!item.user_id} title={!item.user_id?"Link a verified BubsBookings account before activation":undefined} onClick={()=>void action({action:"affiliate_status",targetId:item.id,status:"active",code:item.affiliate_code,programId:item.program_id})} className="rounded-full bg-[#183126] px-4 py-2 text-xs font-bold text-white disabled:cursor-not-allowed disabled:opacity-45">Activate</button>}
      {item.status==="active"&&<button type="button" disabled={busy===item.id} onClick={()=>void action({action:"affiliate_status",targetId:item.id,status:"paused",code:item.affiliate_code,programId:item.program_id,reason:"Paused by administrator"})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold disabled:opacity-60">Pause</button>}
      {Number(item.payable_cents)>0&&<button onClick={()=>void action({action:"payout_create",targetId:item.id})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">Create payout</button>}
      <button disabled={busy===item.id} onClick={()=>setDialog({kind:"readiness",item})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">{item.tax_onboarding_status==="complete"?"Tax review complete ✓":"Verify tax readiness"}</button>
      <button disabled={busy===item.id} onClick={()=>setDialog({kind:"adjustment",item})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">Manual adjustment</button>
      <button disabled={busy===item.id} onClick={()=>setDialog({kind:"terms",item})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">Edit compensation</button>
      {item.milestone_bonuses_enabled===true&&item.milestone_backfill_approved!==true&&<button type="button" disabled={busy===item.id} onClick={()=>setDialog({kind:"historical",item})} className="rounded-full bg-[#eee25a] px-4 py-2 text-xs font-bold disabled:opacity-60">Approve historical milestones</button>}
      {item.affiliate_code&&<button type="button" disabled={busy===item.id} onClick={()=>void copyAffiliateCode(String(item.affiliate_code))} aria-label={`Copy affiliate code ${String(item.affiliate_code)}`} className="rounded-full bg-white px-4 py-2 text-xs font-bold">{copiedCode===item.affiliate_code?"Copied ✓":`Code: ${String(item.affiliate_code)}`}</button>}
    </div><div className="mt-3 grid gap-2 rounded-xl bg-white p-3 text-xs sm:grid-cols-2 lg:grid-cols-4"><p><strong>Program type</strong><br/>{label(item.compensation_type)}</p><p><strong>Activation bonus</strong><br/>{item.activation_bonus_enabled===true?`Enabled · ${money(item.activation_bonus_cents)}`:"Disabled"}</p><p><strong>Provider Growth</strong><br/>{item.milestone_bonuses_enabled===true?`Enabled · ${Number(item.active_provider_count??0)} active`:"Disabled"}</p><p><strong>Revenue share</strong><br/>{item.revenue_share_enabled===true?`Enabled · ${Number(item.revenue_share_basis_points)/100}% for ${item.revenue_share_duration_months} months`:"Disabled"}</p><p><strong>Custom campaign</strong><br/>{item.custom_campaign_enabled===true?`Enabled · ${money(item.custom_campaign_amount_cents)}`:"Disabled"}</p></div>{item.milestone_bonuses_enabled===true&&item.milestone_backfill_approved!==true?<p className="mt-2 text-xs font-bold text-[#8b6b12]">Historical milestone approval is required before any prior activity can create a bonus.</p>:null}</article>)}</div></section>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Programs</h2><div className="mt-4 grid gap-3">{data.programs.map(program=><article key={String(program.id)} className="rounded-2xl bg-[#f8f8f4] p-4"><div className="flex justify-between gap-3"><strong>{program.name}</strong><span className="text-xs font-bold">{label(program.status)}</span></div><p className="mt-2 text-xs leading-5 text-[#687970]">{money(program.activation_bonus_cents)} activation · {Number(program.revenue_share_basis_points)/100}% share · {program.revenue_share_duration_months} months · {program.attribution_window_days}-day attribution · {program.hold_period_days}-day hold · {money(program.minimum_payout_cents)} minimum</p><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setProgramDialog(program)} className="rounded-full border border-[#183126]/15 bg-white px-3 py-2 text-xs font-bold">Edit</button>{program.status!=="enabled"&&<button onClick={()=>void action({action:"program_status",targetId:program.id,status:"enabled"})} className="rounded-full bg-[#183126] px-3 py-2 text-xs font-bold text-white">Enable</button>}{program.status==="enabled"&&<button onClick={()=>void action({action:"program_status",targetId:program.id,status:"disabled"})} className="rounded-full border px-3 py-2 text-xs font-bold">Disable</button>}</div></article>)}</div></section>
    <form onSubmit={createProgram} className="rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Create draft program</h2><p className="mt-2 text-sm text-[#687970]">Create the terms first, then enable the program when it is ready for new partners.</p><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["name","Program name","text",""],["activationBonus","Activation bonus ($)","number","10"],["revenueSharePercent","Revenue share (%)","number","20"],["durationMonths","Share duration (months)","number","6"],["attributionDays","Attribution window (days)","number","60"],["holdDays","Hold period (days)","number","14"],["minimumPayout","Minimum payout ($)","number","50"]].map(([name,title,type,placeholder])=><label key={name} className="text-sm font-bold">{title}<input name={name} type={type} required min={name==="attributionDays"?"1":type==="number"?"0":undefined} max={name==="revenueSharePercent"?"100":name==="attributionDays"||name==="holdDays"?"365":undefined} step={type==="number"&&!["durationMonths","attributionDays","holdDays"].includes(name)?"0.01":type==="number"?"1":undefined} defaultValue={placeholder} className="mt-2 w-full rounded-xl border border-[#183126]/15 px-3 py-3 text-base"/></label>)}</div><label className="mt-3 block text-sm font-bold">Description<textarea name="description" rows={3} className="mt-2 w-full rounded-xl border border-[#183126]/15 px-3 py-3 text-base"/></label>{error&&<p role="alert" className="mt-4 rounded-xl bg-[#fff0e7] p-3 text-sm font-bold text-[#9a4e25]">{error}</p>}<button disabled={busy==="program"} className="mt-4 min-h-11 rounded-full bg-[#eee25a] px-5 py-3 text-sm font-bold disabled:opacity-60">{busy==="program"?"Creating…":"Create draft"}</button></form></div>
    <section className="mt-8 rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Commission ledger</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Partner</th><th>Provider</th><th>Type</th><th>Eligible revenue</th><th>Commission</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.commissions.map(item=><tr key={String(item.id)} className="border-b border-[#183126]/8"><td className="p-3 font-bold">{item.affiliate_name}</td><td>{item.provider_name}</td><td>{label(item.commission_type)}</td><td>{money(item.eligible_revenue_cents)}</td><td className="font-bold">{money(item.amount_cents)}</td><td>{label(item.status)}</td><td><CustomSelect ariaLabel="Change commission status" value="" onChange={(value)=>{const status=value;if(!status)return;if(status==="reverse"){setConfirmDialog({kind:"reversal",item});return;}if(["rejected","disputed"].includes(status)){setConfirmDialog({kind:"commission",item,status});return;}void action({action:"commission_status",targetId:item.id,status,reason:""});}} buttonClassName="rounded-lg border p-2"><option value="">Change…</option><option value="hold">Hold</option><option value="approved">Approve</option><option value="payable">Payable</option><option value="disputed">Disputed</option><option value="rejected">Reject</option><option value="reverse">Reverse…</option></CustomSelect></td></tr>)}</tbody></table></div></section>
    <section className="mt-8 rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Payouts</h2><div className="mt-4 grid gap-3">{data.payouts.length?data.payouts.map(item=><article key={String(item.id)} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#f8f8f4] p-4"><div><strong>{item.affiliate_name} · {money(item.amount_cents)}</strong><p className="text-xs text-[#687970]">{item.commission_count} commissions · {label(item.status)} {item.stripe_transfer_id?`· Stripe ${item.stripe_transfer_id}`:""}</p>{item.failure_reason?<p className="mt-1 text-xs font-bold text-[#9a4e25]">{item.failure_reason}</p>:null}</div>{["pending","failed"].includes(String(item.status))&&<button disabled={busy===item.id} onClick={()=>void action({action:"payout_send",targetId:item.id})} className="rounded-full bg-[#183126] px-4 py-2 text-xs font-bold text-white disabled:opacity-60">{busy===item.id?"Sending…":item.status==="failed"?"Retry Stripe payout":"Send with Stripe"}</button>}</article>):<p className="text-sm text-[#687970]">No affiliate payouts yet.</p>}</div></section>
    <section className="mt-8 rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#687970]">Separate from affiliate commissions</p><h2 className="mt-1 text-2xl font-bold">Creator campaign payments</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#687970]">Record negotiated fixed campaign fees and their status without adding them to referral commissions or automatic Stripe payouts.</p></div></div>
      <form onSubmit={createCampaign} className="mt-5 rounded-2xl bg-[#f8f8f4] p-4"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
        <label className="text-sm font-bold">Creator<CustomSelect ariaLabel="Creator" searchable name="affiliateId" required buttonClassName="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"><option value="">Choose creator</option>{data.affiliates.map(item=><option key={String(item.id)} value={String(item.id)}>{item.display_name}</option>)}</CustomSelect></label>
        <label className="text-sm font-bold">Campaign<input name="campaignName" required maxLength={160} className="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base" placeholder="September launch video"/></label>
        <label className="text-sm font-bold">Fixed payment ($)<input name="fixedAmount" required type="number" min="0" step="0.01" defaultValue="500" className="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"/></label>
        <label className="text-sm font-bold">Payment status<CustomSelect ariaLabel="Payment status" name="paymentStatus" defaultValue="planned" buttonClassName="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"><option value="planned">Planned</option><option value="approved">Approved</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></CustomSelect></label>
        <label className="text-sm font-bold">Campaign starts<DatePicker name="startsOn" ariaLabel="Campaign start date" className="mt-2" buttonClassName="rounded-xl bg-white px-3 py-3 text-base" clearable /></label>
        <label className="text-sm font-bold">Campaign ends<DatePicker name="endsOn" ariaLabel="Campaign end date" className="mt-2" buttonClassName="rounded-xl bg-white px-3 py-3 text-base" clearable /></label>
        <label className="text-sm font-bold">Affiliate program<CustomSelect ariaLabel="Affiliate program" searchable name="programId" buttonClassName="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"><option value="">No linked program</option>{data.programs.map(program=><option key={String(program.id)} value={String(program.id)}>{program.name}</option>)}</CustomSelect></label>
        <label className="text-sm font-bold">Referral code <span className="font-normal text-[#718078]">(optional snapshot)</span><input name="affiliateCode" maxLength={32} pattern="[A-Za-z0-9_-]+" className="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"/></label>
        <label className="text-sm font-bold">Revenue share (%) <span className="font-normal text-[#718078]">(optional)</span><input name="revenueSharePercent" type="number" min="0" max="100" step="0.01" defaultValue="20" className="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"/></label>
        <label className="text-sm font-bold">Share duration (months) <span className="font-normal text-[#718078]">(optional)</span><input name="durationMonths" type="number" min="0" step="1" defaultValue="6" className="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"/></label>
        <label className="text-sm font-bold">Payment reference <span className="font-normal text-[#718078]">(optional)</span><input name="paymentReference" maxLength={200} className="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"/></label>
        <label className="text-sm font-bold sm:col-span-2">Notes <span className="font-normal text-[#718078]">(optional)</span><textarea name="notes" maxLength={2000} rows={3} className="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base"/></label>
      </div><button disabled={busy==="campaign"} className="mt-4 min-h-11 rounded-full bg-[#eee25a] px-5 py-3 text-sm font-bold disabled:opacity-60">{busy==="campaign"?"Saving…":"Record campaign"}</button></form>
      <div className="mt-5 grid gap-3">{data.campaigns.length?data.campaigns.map(item=><article key={String(item.id)} className="rounded-2xl border border-[#183126]/10 bg-[#f8f8f4] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="font-bold">{item.campaign_name} · {item.affiliate_name}</h3><p className="mt-1 text-xs leading-5 text-[#687970]">{money(item.fixed_amount_cents)} fixed fee · {item.program_name||"No linked program"} · {item.affiliate_code?`Code ${item.affiliate_code}`:"No code snapshot"}{item.revenue_share_basis_points!==null?` · ${Number(item.revenue_share_basis_points)/100}% for ${item.revenue_share_duration_months??0} months`:""}</p><p className="text-xs text-[#687970]">{item.campaign_starts_on||"No start"} → {item.campaign_ends_on||"No end"}{item.payment_reference?` · Ref ${item.payment_reference}`:""}</p>{item.notes?<p className="mt-2 whitespace-pre-wrap text-sm">{item.notes}</p>:null}</div><label className="text-xs font-bold">Payment status<CustomSelect ariaLabel={`Payment status for ${item.campaign_name}`} value={String(item.payment_status)} onChange={(value)=>void action({action:"campaign_status",targetId:item.id,status:value,reason:"Campaign status changed by administrator"})} buttonClassName="mt-1 block min-h-11 rounded-xl border bg-white px-3"><option value="planned">Planned</option><option value="approved">Approved</option><option value="paid">Paid</option><option value="cancelled">Cancelled</option></CustomSelect></label></div></article>):<p className="text-sm text-[#687970]">No fixed-fee creator campaigns recorded.</p>}</div>
    </section>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Recent referral visits</h2><div className="mt-4 grid gap-3">{data.recentClicks.slice(0,20).map(item=><article key={String(item.id)} className="rounded-2xl bg-[#f8f8f4] p-4 text-sm"><strong>{item.affiliate_name}</strong><p className="mt-1 break-all text-xs text-[#687970]">{item.landing_path} · {item.utm_campaign||"No campaign"} · {item.created_at?new Date(item.created_at).toLocaleString():""}</p></article>)}</div></section><section className="rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Audit history</h2><div className="mt-4 grid gap-3">{data.auditHistory.slice(0,20).map(item=><article key={String(item.id)} className="rounded-2xl bg-[#f8f8f4] p-4 text-sm"><strong>{label(item.action)}</strong><p className="mt-1 text-xs text-[#687970]">{item.actor_name||"System"} · {label(item.target_type)} · {item.created_at?new Date(item.created_at).toLocaleString():""}</p></article>)}</div></section></div>
    {dialog&&<PartnerActionDialog dialog={dialog} programs={data.programs} busy={busy===dialog.item.id} error={error} onClose={()=>{setDialog(null);setError("");}} onSubmit={submitPartnerDialog}/>}
    {programDialog&&<ProgramEditDialog program={programDialog} busy={busy===programDialog.id} error={error} onClose={()=>{setProgramDialog(null);setError("");}} onSubmit={updateProgram}/>}
    {confirmDialog&&<ConfirmActionDialog dialog={confirmDialog} busy={busy===confirmDialog.item.id} error={error} onClose={()=>{setConfirmDialog(null);setError("");}} onSubmit={submitConfirmDialog}/>}
  </div>;
}

function PartnerActionDialog({dialog,programs,busy,error,onClose,onSubmit}:{dialog:PartnerDialog;programs:ProgramItem[];busy:boolean;error:string;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){
  const formRef=useRef<HTMLFormElement>(null); const returnFocus=useRef<HTMLElement|null>(null);
  useEffect(()=>{returnFocus.current=document.activeElement as HTMLElement;const form=formRef.current;form?.querySelector<HTMLElement>("button, input, textarea, select")?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!busy)onClose();if(event.key!=="Tab"||!form)return;const items=Array.from(form.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), textarea:not([disabled]), select:not([disabled])'));if(!items.length)return;const first=items[0],last=items[items.length-1];if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);returnFocus.current?.focus();};},[busy,onClose]);
  const ready=dialog.item.tax_onboarding_status==="complete";
  const titles={approve:dialog.approvalMode==="custom"?"Approve as Custom Partner":"Approve as Standard Partner",readiness:ready?"Remove tax readiness":"Verify tax readiness",adjustment:"Add manual adjustment",terms:"Set custom terms",historical:"Approve historical milestones"};
  const inputClass="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-4 py-3 text-base outline-none focus:border-[#4d725d] focus:ring-2 focus:ring-[#4d725d]/15";
  const noReferral=dialog.kind==="adjustment"&&Number(dialog.item.referrals)<1;
  return createPortal(<div role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}} className="fixed inset-0 z-[300] grid place-items-end bg-[#07180f]/55 p-0 sm:place-items-center sm:p-5">
    <form ref={formRef} role="dialog" aria-modal="true" aria-labelledby="partner-action-title" onSubmit={onSubmit} className="flex max-h-[calc(100dvh-1rem)] w-full flex-col overflow-hidden rounded-t-[2rem] bg-[#f8f8f4] shadow-2xl sm:max-h-[min(44rem,calc(100dvh-2.5rem))] sm:max-w-xl sm:rounded-[2rem]">
      <div className="flex shrink-0 items-start justify-between gap-4 border-b border-[#183126]/10 px-5 pb-4 pt-5 sm:px-7 sm:pt-7"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#718078]">{dialog.item.display_name}</p><h2 id="partner-action-title" className="mt-1 text-2xl font-bold">{titles[dialog.kind]}</h2></div><button type="button" disabled={busy} onClick={onClose} aria-label="Close" className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[#183126]/15 bg-white"><UiIcon name="close" className="h-5 w-5" /></button></div>
      <div className="min-h-0 overflow-y-auto px-5 py-4 sm:px-7">
        {dialog.kind==="approve"&&<><p className="text-sm leading-6 text-[#687970]">{dialog.approvalMode==="custom"?"Review and configure the custom compensation features. The applicant did not choose these financial terms; admin remains in full control.":"The selected Standard program defaults will apply. These terms are snapshotted on each new referral and existing earnings are never rewritten."}</p><label className="mt-4 block text-sm font-bold">Affiliate program<CustomSelect ariaLabel="Affiliate program" searchable name="programId" required defaultValue={String(dialog.item.program_id??"")} buttonClassName={inputClass}><option value="">Choose a program</option>{programs.filter(program=>program.status==="enabled"||program.id===dialog.item.program_id).filter(program=>dialog.approvalMode!=="standard"||program.program_type==="standard").map(program=><option key={String(program.id)} value={String(program.id)}>{String(program.name)}{program.status!=="enabled"?` (${label(program.status)})`:""}</option>)}</CustomSelect></label><label className="mt-4 block text-sm font-bold">Affiliate code<input name="code" required minLength={3} maxLength={32} pattern="[A-Za-z0-9_-]+" defaultValue={String(dialog.item.affiliate_code||suggestedCode(dialog.item.display_name))} className={inputClass}/></label>{dialog.approvalMode==="custom"&&<CompensationFields item={{...dialog.item,compensation_type:"custom"}} inputClass={inputClass}/>}</>}
        {dialog.kind==="readiness"&&<><p className="text-sm leading-6 text-[#687970]">{ready?"This prevents new payouts until the partner's tax readiness is verified again.":"Only confirm this after checking the required tax information. Stripe payout readiness is verified automatically."}</p><label className="mt-4 block text-sm font-bold">Admin verification note<textarea name="reason" required rows={3} className={`${inputClass} resize-y`} placeholder={ready?"Why tax readiness is being removed":"What tax information or documentation was verified"}/></label></>}
        {dialog.kind==="adjustment"&&(noReferral?<div className="rounded-2xl bg-[#fff1bf] p-4 text-sm leading-6 text-[#6f5d1c]"><strong>Not available yet.</strong> Manual adjustments must be connected to a referred provider. This partner has not referred a provider yet.</div>:<><p className="text-sm leading-6 text-[#687970]">Enter a positive credit or a negative correction. Every adjustment is recorded in the audit log.</p><label className="mt-4 block text-sm font-bold">Amount in dollars<input name="amount" required type="number" step="0.01" className={inputClass} placeholder="25.00 or -25.00"/></label><label className="mt-4 block text-sm font-bold">Reason<textarea name="reason" required rows={3} className={`${inputClass} resize-y`}/></label></>)}
        {dialog.kind==="terms"&&<><p className="rounded-2xl bg-[#fff8d8] p-4 text-sm leading-6">Changes apply only to future referral snapshots. Existing commissions, attribution, payout history, and historical ledger entries remain unchanged. Enabling milestones requires a separate historical-liability approval.</p><CompensationFields item={dialog.item} inputClass={inputClass}/></>}
        {dialog.kind==="historical"&&<><div className="rounded-2xl border border-[#b78e2e]/25 bg-[#fff8d8] p-4 text-sm leading-6"><strong>This can create real bonus liabilities.</strong> Confirm that the historical Active Provider count and liability report have been reviewed. Eligible milestones are created once and enter the normal holding and payout workflow.</div><label className="mt-4 block text-sm font-bold">Approval note<textarea name="reason" required maxLength={1000} rows={3} className={`${inputClass} resize-y`} placeholder="What was reviewed and approved"/></label></>}
        {error&&<p role="alert" className="mt-4 rounded-xl bg-[#fff0e7] p-3 text-sm font-bold text-[#9a4e25]">{error}</p>}
      </div>
      <div className="flex shrink-0 flex-col-reverse gap-2 border-t border-[#183126]/10 bg-[#f8f8f4] px-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-4 sm:flex-row sm:justify-end sm:px-7 sm:pb-5"><button type="button" disabled={busy} onClick={onClose} className="min-h-11 rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold">Cancel</button>{!noReferral&&<button disabled={busy} className="min-h-11 rounded-full bg-[#183126] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?"Saving…":dialog.kind==="historical"?"Approve milestones":"Save changes"}</button>}</div>
    </form>
  </div>,document.body);
}

function CompensationFields({item,inputClass}:{item:AffiliateItem;inputClass:string}){
  const [activation,setActivation]=useState(item.activation_bonus_enabled===undefined||item.activation_bonus_enabled===null?true:item.activation_bonus_enabled===true);
  const [milestones,setMilestones]=useState(item.milestone_bonuses_enabled===undefined||item.milestone_bonuses_enabled===null?true:item.milestone_bonuses_enabled===true);
  const [revenue,setRevenue]=useState(item.revenue_share_enabled===undefined||item.revenue_share_enabled===null?true:item.revenue_share_enabled===true);
  const [campaign,setCampaign]=useState(item.custom_campaign_enabled===true);
  const switchClass="flex min-h-14 items-center justify-between gap-4 rounded-2xl border border-[#183126]/15 bg-white px-4 py-3 text-sm font-bold";
  const dateValue=(value:unknown)=>value?String(value).slice(0,10):"";
  return <fieldset className="mt-5"><legend className="text-base font-bold">Compensation settings</legend><label className="mt-3 block text-sm font-bold">Program type<CustomSelect ariaLabel="Program type" name="compensationType" defaultValue={String(item.compensation_type??"standard")} buttonClassName={inputClass}><option value="standard">Standard</option><option value="custom">Custom</option></CustomSelect></label><div className="mt-4 grid gap-3 sm:grid-cols-2">
    <label className={switchClass}><span>Activation Bonus<br/><small className="font-normal text-[#687970]">{activation?"Enabled":"Disabled"}</small></span><input name="activationBonusEnabled" type="checkbox" checked={activation} onChange={event=>setActivation(event.target.checked)} className="h-5 w-5 accent-[#34704a]"/></label>
    <label className={switchClass}><span>Provider Growth Milestones<br/><small className="font-normal text-[#687970]">{milestones?"Enabled":"Disabled"}</small></span><input name="milestoneBonusesEnabled" type="checkbox" checked={milestones} onChange={event=>setMilestones(event.target.checked)} className="h-5 w-5 accent-[#34704a]"/></label>
    <label className={switchClass}><span>Revenue Share<br/><small className="font-normal text-[#687970]">{revenue?"Enabled":"Disabled"}</small></span><input name="revenueShareEnabled" type="checkbox" checked={revenue} onChange={event=>setRevenue(event.target.checked)} className="h-5 w-5 accent-[#34704a]"/></label>
    <label className={switchClass}><span>Custom Campaign<br/><small className="font-normal text-[#687970]">{campaign?"Enabled":"Disabled"}</small></span><input name="customCampaignEnabled" type="checkbox" checked={campaign} onChange={event=>setCampaign(event.target.checked)} className="h-5 w-5 accent-[#34704a]"/></label>
  </div><div className="mt-4 grid gap-4 sm:grid-cols-2">{activation?<label className="text-sm font-bold">Activation bonus ($)<input name="activationBonus" required type="number" min="0" step="0.01" defaultValue={Number(item.activation_bonus_cents??1000)/100} className={inputClass}/></label>:<input type="hidden" name="activationBonus" value="0"/>}<label className="text-sm font-bold">Minimum payout ($)<input name="minimumPayout" required type="number" min="0" step="0.01" defaultValue={Number(item.minimum_payout_cents??5000)/100} className={inputClass}/></label>{revenue?<><label className="text-sm font-bold">Revenue share (%)<input name="revenueSharePercent" required type="number" min="0.01" max="100" step="0.01" defaultValue={Number(item.revenue_share_basis_points??2000)/100} className={inputClass}/></label><label className="text-sm font-bold">Revenue-share duration (months)<input name="durationMonths" required type="number" min="1" step="1" defaultValue={Number(item.revenue_share_duration_months??6)} className={inputClass}/><span className="mt-1 block text-xs font-normal leading-5 text-[#687970]">How long eligible referred-provider revenue share continues from that referral&apos;s configured share-start event. Campaign dates do not end it.</span></label></>:<><input type="hidden" name="revenueSharePercent" value="0"/><input type="hidden" name="durationMonths" value="0"/></>}</div>
  {campaign?<div className="mt-4 grid gap-4 rounded-2xl border border-[#183126]/10 bg-white p-4 sm:grid-cols-2"><label className="text-sm font-bold">Fixed campaign amount ($)<input name="customCampaignAmount" required type="number" min="0.01" step="0.01" defaultValue={Number(item.custom_campaign_amount_cents??50000)/100} className={inputClass}/></label><span/><label className="text-sm font-bold">Campaign start<span className="mt-1 block text-xs font-normal leading-5 text-[#687970]">Starts the fixed promotional campaign period only.</span><DatePicker name="customCampaignStartsOn" required defaultValue={dateValue(item.custom_campaign_starts_on)} ariaLabel="Custom campaign start date" buttonClassName={inputClass}/></label><label className="text-sm font-bold">Campaign end<span className="mt-1 block text-xs font-normal leading-5 text-[#687970]">Ends the fixed promotional campaign period only; it does not end revenue share.</span><DatePicker name="customCampaignEndsOn" required defaultValue={dateValue(item.custom_campaign_ends_on)} ariaLabel="Custom campaign end date" buttonClassName={inputClass}/></label><label className="text-sm font-bold sm:col-span-2">Campaign notes <span className="font-normal text-[#687970]">(admin only)</span><textarea name="customCampaignNotes" maxLength={2000} rows={3} defaultValue={String(item.custom_campaign_notes??"")} className={`${inputClass} resize-y`}/></label></div>:<><input type="hidden" name="customCampaignAmount" value="0"/><input type="hidden" name="customCampaignStartsOn" value=""/><input type="hidden" name="customCampaignEndsOn" value=""/><input type="hidden" name="customCampaignNotes" value=""/></>}
  </fieldset>;
}

function ProgramEditDialog({program,busy,error,onClose,onSubmit}:{program:ProgramItem;busy:boolean;error:string;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){
  const formRef=useRef<HTMLFormElement>(null); const returnFocus=useRef<HTMLElement|null>(null);
  useEffect(()=>{returnFocus.current=document.activeElement as HTMLElement;formRef.current?.querySelector<HTMLElement>("input, textarea, button")?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!busy)onClose();};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);returnFocus.current?.focus();};},[busy,onClose]);
  const inputClass="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-4 py-3 text-base outline-none focus:border-[#4d725d] focus:ring-2 focus:ring-[#4d725d]/15";
  const fields:Array<[string,string,string|number,number,string|undefined]>=[
    ["activationBonus","Activation bonus ($)",Number(program.activation_bonus_cents)/100,0,"0.01"],
    ["revenueSharePercent","Revenue share (%)",Number(program.revenue_share_basis_points)/100,0,"0.01"],
    ["durationMonths","Share duration (months)",Number(program.revenue_share_duration_months),0,"1"],
    ["attributionDays","Attribution window (days)",Number(program.attribution_window_days),1,"1"],
    ["holdDays","Hold period (days)",Number(program.hold_period_days),0,"1"],
    ["minimumPayout","Minimum payout ($)",Number(program.minimum_payout_cents)/100,0,"0.01"],
  ];
  return createPortal(<div role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}} className="fixed inset-0 z-[305] grid place-items-end bg-[#07180f]/55 p-0 sm:place-items-center sm:p-5">
    <form ref={formRef} role="dialog" aria-modal="true" aria-labelledby="program-edit-title" onSubmit={onSubmit} className="flex max-h-[calc(100dvh-1rem)] w-full flex-col overflow-hidden rounded-t-[2rem] bg-[#f8f8f4] shadow-2xl sm:max-h-[min(48rem,calc(100dvh-2.5rem))] sm:max-w-2xl sm:rounded-[2rem]">
      <div className="flex shrink-0 items-start justify-between gap-4 border-b border-[#183126]/10 px-5 pb-4 pt-5 sm:px-7 sm:pt-7"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#718078]">Affiliate program</p><h2 id="program-edit-title" className="mt-1 text-2xl font-bold">Edit {program.name}</h2></div><button type="button" disabled={busy} onClick={onClose} aria-label="Close" className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[#183126]/15 bg-white"><UiIcon name="close" className="h-5 w-5" /></button></div>
      <div className="min-h-0 overflow-y-auto px-5 py-4 sm:px-7"><p className="rounded-2xl bg-[#edf3e7] p-4 text-sm leading-6 text-[#365944]">Changes apply to this program and future referrals. Terms already snapshotted onto existing referrals are not rewritten.</p><label className="mt-4 block text-sm font-bold">Program name<input name="name" required maxLength={120} defaultValue={String(program.name)} className={inputClass}/></label><div className="mt-4 grid gap-4 sm:grid-cols-2">{fields.map(([name,title,value,min,step])=><label key={name} className="text-sm font-bold">{title}<input name={name} required type="number" min={min} max={name==="revenueSharePercent"?100:name==="attributionDays"||name==="holdDays"?365:undefined} step={step} defaultValue={value} className={inputClass}/></label>)}</div><label className="mt-4 block text-sm font-bold">Description<textarea name="description" maxLength={1000} rows={4} defaultValue={String(program.description??"")} className={`${inputClass} resize-y`}/></label>{error&&<p role="alert" className="mt-4 rounded-xl bg-[#fff0e7] p-3 text-sm font-bold text-[#9a4e25]">{error}</p>}</div>
      <div className="flex shrink-0 flex-col-reverse gap-2 border-t border-[#183126]/10 px-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-4 sm:flex-row sm:justify-end sm:px-7 sm:pb-5"><button type="button" disabled={busy} onClick={onClose} className="min-h-11 rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold">Cancel</button><button disabled={busy} className="min-h-11 rounded-full bg-[#183126] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?"Saving…":"Save program"}</button></div>
    </form>
  </div>,document.body);
}

function ConfirmActionDialog({dialog,busy,error,onClose,onSubmit}:{dialog:ConfirmDialog;busy:boolean;error:string;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){
  const dialogRef=useRef<HTMLFormElement>(null); const returnFocus=useRef<HTMLElement|null>(null);
  useEffect(()=>{returnFocus.current=document.activeElement as HTMLElement;dialogRef.current?.querySelector<HTMLElement>("input, textarea, button")?.focus();const key=(event:KeyboardEvent)=>{if(event.key==="Escape"&&!busy)onClose();};document.addEventListener("keydown",key);return()=>{document.removeEventListener("keydown",key);returnFocus.current?.focus();};},[busy,onClose]);
  const title=dialog.kind==="reversal"?"Reverse commission":`${label(dialog.status)} commission`;
  return createPortal(<div role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}} className="fixed inset-0 z-[310] grid place-items-end bg-[#07180f]/55 sm:place-items-center sm:p-5"><form ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="confirm-action-title" onSubmit={onSubmit} className="w-full rounded-t-[2rem] bg-[#f8f8f4] p-5 shadow-2xl sm:max-w-lg sm:rounded-[2rem] sm:p-7"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-wider text-[#718078]">{dialog.item.affiliate_name||"Partner operations"}</p><h2 id="confirm-action-title" className="mt-1 text-2xl font-bold">{title}</h2></div><button type="button" disabled={busy} onClick={onClose} aria-label="Close" className="grid h-11 w-11 shrink-0 place-items-center rounded-full border bg-white text-xl">×</button></div><p className="mt-4 text-sm leading-6 text-[#687970]">A clear reason is required and will be retained in the affiliate audit history.</p><label className="mt-4 block text-sm font-bold">Reason<textarea name="reason" required maxLength={1000} rows={3} className="mt-2 w-full resize-y rounded-xl border px-4 py-3 text-base"/></label>{error&&<p role="alert" className="mt-4 rounded-xl bg-[#fff0e7] p-3 text-sm font-bold text-[#9a4e25]">{error}</p>}<div className="mt-5 flex flex-col-reverse gap-2 pb-[env(safe-area-inset-bottom)] sm:flex-row sm:justify-end"><button type="button" onClick={onClose} disabled={busy} className="min-h-11 rounded-full border bg-white px-5 font-bold">Cancel</button><button disabled={busy} className="min-h-11 rounded-full bg-[#183126] px-5 font-bold text-white">{busy?"Saving…":"Confirm"}</button></div></form></div>,document.body);
}
