"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { createPortal } from "react-dom";

type Data = {
  summary: Record<string, number>;
  programs: Array<Record<string, string | number | string[] | null>>;
  affiliates: Array<Record<string, string | number | null>>;
  commissions: Array<Record<string, string | number | null>>;
  payouts: Array<Record<string, string | number | null>>;
  recentClicks: Array<Record<string, string | null>>;
};
type AffiliateItem = Record<string, string | number | null>;
type PartnerDialog = { kind: "approve" | "readiness" | "adjustment" | "terms"; item: AffiliateItem };
const money = (value: unknown) => new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" }).format(Number(value ?? 0) / 100);
const label = (value: unknown) => String(value ?? "").replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase());
const suggestedCode = (value: unknown) => String(value ?? "PARTNER").toUpperCase().replace(/[^A-Z0-9]/g, "").slice(0, 20);

export default function AffiliateAdmin() {
  const [data,setData]=useState<Data|null>(null); const [error,setError]=useState(""); const [notice,setNotice]=useState(""); const [busy,setBusy]=useState("");
  const [dialog,setDialog]=useState<PartnerDialog|null>(null);
  const load=useCallback(async()=>{const response=await fetch("/api/admin/affiliates",{cache:"no-store"}); if(!response.ok){setError("Partner data could not be loaded.");return;} setData(await response.json());setError("");},[]);
  useEffect(()=>{let active=true;fetch("/api/admin/affiliates",{cache:"no-store"}).then(async response=>response.ok?response.json() as Promise<Data>:null).catch(()=>null).then(result=>{if(!active)return;if(result)setData(result);else setError("Partner data could not be loaded.");});return()=>{active=false;};},[]);
  useEffect(()=>{if(!dialog)return;const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{document.body.style.overflow=previous;};},[dialog]);
  async function action(body: Record<string,unknown>){setBusy(String(body.targetId??body.action));setError("");setNotice("");try{const response=await fetch("/api/admin/affiliates",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json() as {error?:string};if(!response.ok){setError(result.error??"Action failed.");return false;}setNotice("Partner records updated.");await load();return true;}catch{setError("The partner update could not be sent. Please try again.");return false;}finally{setBusy("");}}
  async function submitPartnerDialog(event: FormEvent<HTMLFormElement>){
    event.preventDefault();
    if(!dialog)return;
    const values=Object.fromEntries(new FormData(event.currentTarget));
    let body:Record<string,unknown>={targetId:dialog.item.id};
    if(dialog.kind==="approve")body={...body,action:"affiliate_status",status:"approved",code:values.code,programId:dialog.item.program_id};
    if(dialog.kind==="readiness")body={...body,action:"affiliate_payment_readiness",ready:!(dialog.item.payment_status==="ready"&&dialog.item.tax_onboarding_status==="complete"),reason:values.reason};
    if(dialog.kind==="adjustment")body={...body,action:"manual_adjustment",amount:values.amount,reason:values.reason};
    if(dialog.kind==="terms")body={...body,action:"affiliate_overrides",activationBonus:values.activationBonus,revenueSharePercent:values.revenueSharePercent,durationMonths:values.durationMonths,minimumPayout:values.minimumPayout,reason:values.reason};
    if(await action(body))setDialog(null);
  }
  async function createProgram(event: FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);setBusy("program");const response=await fetch("/api/admin/affiliates",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"program_create",...Object.fromEntries(form)})});const result=await response.json() as {error?:string};setBusy("");if(!response.ok){setError(result.error??"Program could not be created.");return;}event.currentTarget.reset();setNotice("Draft program created.");await load();}
  if(!data)return <div className="dashboard-container px-5 py-12">{error||"Loading partner operations…"}</div>;
  const metrics=[["Applications",data.summary.applications],["Active partners",data.summary.active_affiliates],["Provider referrals",data.summary.provider_referrals],["Qualified providers",data.summary.qualified_providers],["Pending",money(data.summary.pending_cents)],["Payable",money(data.summary.payable_cents)],["Paid",money(data.summary.paid_cents)]];
  return <div className="dashboard-container px-5 py-10"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-[#687970]">Marketplace growth</p><h1 className="mt-2 text-4xl font-bold">Partners &amp; affiliates</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-[#687970]">Review applications, manage configurable programs, inspect referrals, approve ledger entries, and issue audited manual payouts.</p></div>
    {(error||notice)&&<p role="status" className={`mt-5 rounded-2xl p-4 text-sm font-bold ${error?"bg-[#fff0e7] text-[#9a4e25]":"bg-[#e5f1e5] text-[#34704a]"}`}>{error||notice}</p>}
    <section className="mt-7 grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7">{metrics.map(([name,value])=><article key={name} className="rounded-2xl bg-white p-4"><p className="text-[10px] font-bold uppercase tracking-wider text-[#718078]">{name}</p><p className="mt-2 text-xl font-bold">{value}</p></article>)}</section>
    <section className="mt-8 rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Applications and partners</h2><div className="mt-5 grid gap-4">{data.affiliates.map(item=><article key={String(item.id)} className="rounded-2xl border border-[#183126]/10 bg-[#f8f8f4] p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-bold">{item.display_name}</h3><p className="text-sm text-[#687970]">{item.email} · {item.program_name}</p><p className="mt-1 text-xs text-[#687970]">{item.clicks} clicks · {item.referrals} referrals · {item.qualified} qualified · {money(item.payable_cents)} payable</p></div><span className="rounded-full bg-[#edf3e7] px-3 py-1 text-xs font-bold">{label(item.status)}</span></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6"><strong>Audience:</strong> {item.primary_audience||"Not supplied"}<br/><strong>Plan:</strong> {item.promotion_plan||"Not supplied"}</p><div className="mt-4 flex flex-wrap gap-2">
      {!["approved","active"].includes(String(item.status))&&<button disabled={busy===item.id} onClick={()=>setDialog({kind:"approve",item})} className="rounded-full bg-[#eee25a] px-4 py-2 text-xs font-bold">Approve</button>}
      {item.status==="approved"&&<button onClick={()=>void action({action:"affiliate_status",targetId:item.id,status:"active",code:item.affiliate_code,programId:item.program_id})} className="rounded-full bg-[#183126] px-4 py-2 text-xs font-bold text-white">Activate</button>}
      {item.status==="active"&&<button onClick={()=>void action({action:"affiliate_status",targetId:item.id,status:"paused",code:item.affiliate_code,programId:item.program_id,reason:"Paused by administrator"})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">Pause</button>}
      {Number(item.payable_cents)>0&&<button onClick={()=>void action({action:"payout_create",targetId:item.id})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">Create payout</button>}
      <button disabled={busy===item.id} onClick={()=>setDialog({kind:"readiness",item})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">{item.payment_status==="ready"&&item.tax_onboarding_status==="complete"?"Payout ready ✓":"Verify payout readiness"}</button>
      <button disabled={busy===item.id} onClick={()=>setDialog({kind:"adjustment",item})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">Manual adjustment</button>
      <button disabled={busy===item.id} onClick={()=>setDialog({kind:"terms",item})} className="rounded-full border border-[#183126]/15 px-4 py-2 text-xs font-bold">Custom terms</button>
      {item.affiliate_code&&<span className="rounded-full bg-white px-4 py-2 text-xs font-bold">Code: {item.affiliate_code}</span>}
    </div></article>)}</div></section>
    <div className="mt-8 grid gap-6 xl:grid-cols-2"><section className="rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Programs</h2><div className="mt-4 grid gap-3">{data.programs.map(program=><article key={String(program.id)} className="rounded-2xl bg-[#f8f8f4] p-4"><div className="flex justify-between gap-3"><strong>{program.name}</strong><span className="text-xs font-bold">{label(program.status)}</span></div><p className="mt-2 text-xs leading-5 text-[#687970]">{money(program.activation_bonus_cents)} activation · {Number(program.revenue_share_basis_points)/100}% share · {program.revenue_share_duration_months} months · {program.attribution_window_days}-day attribution · {program.hold_period_days}-day hold · {money(program.minimum_payout_cents)} minimum</p><div className="mt-3 flex gap-2">{program.status!=="enabled"&&<button onClick={()=>void action({action:"program_status",targetId:program.id,status:"enabled"})} className="rounded-full bg-[#183126] px-3 py-2 text-xs font-bold text-white">Enable</button>}{program.status==="enabled"&&<button onClick={()=>void action({action:"program_status",targetId:program.id,status:"disabled"})} className="rounded-full border px-3 py-2 text-xs font-bold">Disable</button>}</div></article>)}</div></section>
    <form onSubmit={createProgram} className="rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Create draft program</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{[["name","Program name","text",""],["activationBonus","Activation bonus ($)","number","10"],["revenueSharePercent","Revenue share (%)","number","20"],["durationMonths","Share duration (months)","number","6"],["attributionDays","Attribution window (days)","number","60"],["holdDays","Hold period (days)","number","30"],["minimumPayout","Minimum payout ($)","number","50"]].map(([name,title,type,placeholder])=><label key={name} className="text-sm font-bold">{title}<input name={name} type={type} required min={type==="number"?"0":undefined} step={type==="number"?"0.01":undefined} placeholder={placeholder} className="mt-2 w-full rounded-xl border border-[#183126]/15 px-3 py-3 text-base"/></label>)}</div><label className="mt-3 block text-sm font-bold">Description<textarea name="description" rows={3} className="mt-2 w-full rounded-xl border border-[#183126]/15 px-3 py-3 text-base"/></label><button disabled={busy==="program"} className="mt-4 rounded-full bg-[#eee25a] px-5 py-3 text-sm font-bold">Create draft</button></form></div>
    <section className="mt-8 rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Commission ledger</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[780px] text-left text-sm"><thead><tr className="border-b"><th className="p-3">Partner</th><th>Provider</th><th>Type</th><th>Eligible revenue</th><th>Commission</th><th>Status</th><th>Action</th></tr></thead><tbody>{data.commissions.map(item=><tr key={String(item.id)} className="border-b border-[#183126]/8"><td className="p-3 font-bold">{item.affiliate_name}</td><td>{item.provider_name}</td><td>{label(item.commission_type)}</td><td>{money(item.eligible_revenue_cents)}</td><td className="font-bold">{money(item.amount_cents)}</td><td>{label(item.status)}</td><td><select aria-label="Change commission status" value="" onChange={event=>{const status=event.target.value;if(!status)return;if(status==="reverse"){const reason=prompt("Reversal reason (required)")||"";if(reason)void action({action:"commission_reversal",targetId:item.id,reason});return;}const reason=["rejected","disputed"].includes(status)?prompt("Reason required")||"":"";void action({action:"commission_status",targetId:item.id,status,reason});}} className="rounded-lg border p-2"><option value="">Change…</option><option value="hold">Hold</option><option value="approved">Approve</option><option value="payable">Payable</option><option value="disputed">Disputed</option><option value="rejected">Reject</option><option value="reverse">Reverse…</option></select></td></tr>)}</tbody></table></div></section>
    <section className="mt-8 rounded-[1.75rem] border border-[#183126]/10 bg-white p-5"><h2 className="text-2xl font-bold">Payouts</h2><div className="mt-4 grid gap-3">{data.payouts.length?data.payouts.map(item=><article key={String(item.id)} className="flex flex-wrap items-center justify-between gap-3 rounded-2xl bg-[#f8f8f4] p-4"><div><strong>{item.affiliate_name} · {money(item.amount_cents)}</strong><p className="text-xs text-[#687970]">{item.commission_count} commissions · {label(item.status)} {item.payout_reference?`· ${item.payout_reference}`:""}</p></div>{item.status==="pending"&&<button onClick={()=>{const reference=prompt("Payment reference (required)");if(reference)void action({action:"payout_paid",targetId:item.id,reference});}} className="rounded-full bg-[#183126] px-4 py-2 text-xs font-bold text-white">Mark paid</button>}</article>):<p className="text-sm text-[#687970]">No affiliate payouts yet.</p>}</div></section>
    {dialog&&<PartnerActionDialog dialog={dialog} busy={busy===dialog.item.id} error={error} onClose={()=>{setDialog(null);setError("");}} onSubmit={submitPartnerDialog}/>}
  </div>;
}

function PartnerActionDialog({dialog,busy,error,onClose,onSubmit}:{dialog:PartnerDialog;busy:boolean;error:string;onClose:()=>void;onSubmit:(event:FormEvent<HTMLFormElement>)=>void}){
  const ready=dialog.item.payment_status==="ready"&&dialog.item.tax_onboarding_status==="complete";
  const titles={approve:"Approve partner",readiness:ready?"Remove payout readiness":"Verify payout readiness",adjustment:"Add manual adjustment",terms:"Set custom terms"};
  const inputClass="mt-2 w-full rounded-xl border border-[#183126]/15 bg-white px-4 py-3 text-base outline-none focus:border-[#4d725d] focus:ring-2 focus:ring-[#4d725d]/15";
  const noReferral=dialog.kind==="adjustment"&&Number(dialog.item.referrals)<1;
  return createPortal(<div role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget&&!busy)onClose();}} className="fixed inset-0 z-[300] grid place-items-end bg-[#07180f]/55 p-0 sm:place-items-center sm:p-5">
    <form role="dialog" aria-modal="true" aria-labelledby="partner-action-title" onSubmit={onSubmit} className="flex max-h-[calc(100dvh-1rem)] w-full flex-col overflow-hidden rounded-t-[2rem] bg-[#f8f8f4] shadow-2xl sm:max-h-[min(44rem,calc(100dvh-2.5rem))] sm:max-w-xl sm:rounded-[2rem]">
      <div className="flex shrink-0 items-start justify-between gap-4 border-b border-[#183126]/10 px-5 pb-4 pt-5 sm:px-7 sm:pt-7"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#718078]">{dialog.item.display_name}</p><h2 id="partner-action-title" className="mt-1 text-2xl font-bold">{titles[dialog.kind]}</h2></div><button type="button" disabled={busy} onClick={onClose} aria-label="Close" className="grid h-11 w-11 shrink-0 place-items-center rounded-full border border-[#183126]/15 bg-white text-xl">×</button></div>
      <div className="min-h-0 overflow-y-auto px-5 py-4 sm:px-7">
        {dialog.kind==="approve"&&<><p className="text-sm leading-6 text-[#687970]">Choose the unique code this partner will share. You can activate the partner after approval.</p><label className="mt-4 block text-sm font-bold">Affiliate code<input name="code" required minLength={3} maxLength={32} pattern="[A-Za-z0-9_-]+" defaultValue={suggestedCode(dialog.item.display_name)} className={inputClass}/></label></>}
        {dialog.kind==="readiness"&&<><p className="text-sm leading-6 text-[#687970]">{ready?"This prevents new payouts until payment and tax details are verified again.":"Only confirm this after checking the partner's payment method and required tax information."}</p><label className="mt-4 block text-sm font-bold">Admin verification note<textarea name="reason" required rows={3} className={`${inputClass} resize-y`} placeholder={ready?"Why payout readiness is being removed":"What payment and tax details were verified"}/></label></>}
        {dialog.kind==="adjustment"&&(noReferral?<div className="rounded-2xl bg-[#fff1bf] p-4 text-sm leading-6 text-[#6f5d1c]"><strong>Not available yet.</strong> Manual adjustments must be connected to a referred provider. This partner has not referred a provider yet.</div>:<><p className="text-sm leading-6 text-[#687970]">Enter a positive credit or a negative correction. Every adjustment is recorded in the audit log.</p><label className="mt-4 block text-sm font-bold">Amount in dollars<input name="amount" required type="number" step="0.01" className={inputClass} placeholder="25.00 or -25.00"/></label><label className="mt-4 block text-sm font-bold">Reason<textarea name="reason" required rows={3} className={`${inputClass} resize-y`}/></label></>)}
        {dialog.kind==="terms"&&<><p className="text-sm leading-6 text-[#687970]">Leave a field blank to use the standard program value.</p><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold">Activation bonus ($)<input name="activationBonus" type="number" min="0" step="0.01" className={inputClass}/></label><label className="text-sm font-bold">Revenue share (%)<input name="revenueSharePercent" type="number" min="0" max="100" step="0.01" className={inputClass}/></label><label className="text-sm font-bold">Share duration (months)<input name="durationMonths" type="number" min="0" step="1" className={inputClass}/></label><label className="text-sm font-bold">Minimum payout ($)<input name="minimumPayout" type="number" min="0" step="0.01" className={inputClass}/></label></div><label className="mt-4 block text-sm font-bold">Admin note <span className="font-normal text-[#718078]">(optional)</span><textarea name="reason" rows={3} className={`${inputClass} resize-y`}/></label></>}
        {error&&<p role="alert" className="mt-4 rounded-xl bg-[#fff0e7] p-3 text-sm font-bold text-[#9a4e25]">{error}</p>}
      </div>
      <div className="flex shrink-0 flex-col-reverse gap-2 border-t border-[#183126]/10 bg-[#f8f8f4] px-5 pb-[max(1.25rem,env(safe-area-inset-bottom))] pt-4 sm:flex-row sm:justify-end sm:px-7 sm:pb-5"><button type="button" disabled={busy} onClick={onClose} className="min-h-11 rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold">Cancel</button>{!noReferral&&<button disabled={busy} className="min-h-11 rounded-full bg-[#183126] px-5 py-3 text-sm font-bold text-white disabled:opacity-60">{busy?"Saving…":"Save changes"}</button>}</div>
    </form>
  </div>,document.body);
}
