import Link from "next/link";
import { PLAN_ENTITLEMENTS, type ProviderPlan } from "@/lib/plans";

export default function BillingPanel({ plan }: { plan: ProviderPlan }) {
  const current = PLAN_ENTITLEMENTS[plan];
  return <div><div><p className="text-sm font-semibold text-[#687a70]">Company subscription</p><h1 className="mt-1 text-3xl font-bold tracking-[-.04em] sm:text-4xl">Billing</h1><p className="mt-2 text-sm text-[#687a70]">Review your plan today. Secure billing will be connected here when Stripe is ready.</p></div>
    <div className="mt-7 grid gap-6 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-[2rem] bg-[#183126] p-7 text-white"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.14em] text-[#b4c5bc]">Current plan</p><h2 className="mt-2 text-3xl font-bold">{current.name}</h2></div><span className="rounded-full bg-[#eee25a] px-4 py-2 text-xs font-bold text-[#183126]">Active</span></div><p className="mt-7 text-4xl font-bold">${current.monthlyPrice.toFixed(2)}<span className="text-sm font-normal text-[#b7c7be]"> / month</span></p><div className="mt-6 grid gap-3 sm:grid-cols-2"><BillingFact label="Booking fee" value={`${current.bookingFeePercent}%`} /><BillingFact label="Services" value={current.serviceLimit === null ? "Unlimited" : `Up to ${current.serviceLimit}`} /><BillingFact label="Team seats" value={current.teamSeatLimit === null ? "Unlimited" : String(current.teamSeatLimit)} /><BillingFact label="BookMe AI" value={current.aiAssistant ? "Included" : "Paid plans"} /></div><Link href="/pricing" className="mt-7 inline-flex rounded-full bg-white px-5 py-3 text-sm font-bold text-[#183126] transition hover:bg-[#eee25a]">Compare plans</Link></section>
      <section className="rounded-[2rem] border border-[#d8cb63] bg-[#fff9d9] p-7"><span className="text-3xl">💳</span><h2 className="mt-4 text-xl font-bold">Stripe setup is coming next</h2><p className="mt-2 text-sm leading-6 text-[#706942]">No payment method is required yet, and BookMe is not charging subscription fees. This page is ready for payment methods, invoices, and plan changes when Stripe is connected.</p><div className="mt-5 rounded-2xl bg-white/70 p-4 text-sm"><p className="font-bold">Payment method</p><p className="mt-1 text-[#80784f]">Not connected</p></div></section></div>
    <section className="mt-6 rounded-[2rem] border border-[#183126]/10 bg-white p-7"><div className="flex items-center justify-between"><div><h2 className="text-xl font-bold">Invoice history</h2><p className="mt-1 text-sm text-[#738179]">Your subscription receipts will appear here.</p></div><span className="rounded-full bg-[#edf2e8] px-3 py-1.5 text-xs font-bold">0 invoices</span></div><div className="mt-6 rounded-2xl bg-[#f5f5ef] px-5 py-10 text-center"><p className="text-3xl">▤</p><p className="mt-3 font-bold">No invoices yet</p><p className="mt-1 text-sm text-[#738179]">Billing has not started, so there is nothing to pay.</p></div></section>
  </div>;
}

function BillingFact({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-white/10 p-4"><p className="text-xs text-[#b8c7bf]">{label}</p><p className="mt-1 font-bold">{value}</p></div>; }
