"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Quote = { id: string; providerId: string; serviceId: string; providerName: string; serviceTitle: string; version: number; title: string; description: string; total: number; notes: string; status: string; bookingId: string | null; createdAt: string };
type JobRequest = { id: string; category: string; title: string; description: string; city: string; state: string; postalCode: string; preferredStartsAt: string; flexible: boolean; budgetMin: number | null; budgetMax: number | null; status: string; createdAt: string; matchedServiceId?: string; matchedServiceTitle?: string; distanceMiles?: number; quotes: Quote[] };
type OpportunityMetrics = { opportunities: number; responded: number; accepted: number; responseRate: number | null; averageResponseMinutes: number | null; sampleProtected: boolean };

export default function JobRequestCenter({ mode }: { mode: "customer" | "provider" }) {
  const router = useRouter();
  const [items, setItems] = useState<JobRequest[]>([]); const [metrics, setMetrics] = useState<OpportunityMetrics | null>(null); const [loaded, setLoaded] = useState(false); const [error, setError] = useState(""); const [busy, setBusy] = useState("");
  const load = useCallback(async () => { const response = await fetch(`/api/job-requests${mode === "provider" ? "?view=provider" : ""}`, { cache: "no-store" }); const data = await response.json() as { requests?: JobRequest[]; metrics?: OpportunityMetrics; error?: string }; if (!response.ok) throw new Error(data.error ?? "Requests could not be loaded."); setItems(data.requests ?? []); setMetrics(data.metrics ?? null); }, [mode]);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((reason: Error) => setError(reason.message)).finally(() => setLoaded(true)); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function respond(quoteId: string, action: "accept" | "decline") { setBusy(quoteId); setError(""); const response = await fetch(`/api/quotes/${quoteId}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action }) }); const data = await response.json() as { bookingId?: string; error?: string }; setBusy(""); if (!response.ok) { setError(data.error ?? "The quote could not be updated."); return; } if (action === "accept" && data.bookingId) { router.push(`/account/bookings/${data.bookingId}`); return; } await load(); }
  async function cancel(id: string) { setBusy(id); const response = await fetch(`/api/job-requests/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ action: "cancel" }) }); const data = await response.json() as { error?: string }; setBusy(""); if (!response.ok) setError(data.error ?? "The request could not be cancelled."); else await load(); }
  if (!loaded) return <div className="rounded-[2rem] bg-white p-8 text-sm text-[#718078]">Loading service requests…</div>;
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-[#687a70]">{mode === "provider" ? "New local work" : "Your request inbox"}</p><h1 className="mt-1 text-3xl font-bold tracking-[-.04em] sm:text-4xl">{mode === "provider" ? "Opportunities" : "Service requests"}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[#687a70]">{mode === "provider" ? "Review matched customer needs and send a free quote. You are never charged for the lead or conversation." : "Compare quotes, message providers, and turn the right quote into a secure booking."}</p></div>{mode === "customer" && <Link href="/requests" className="w-fit rounded-full bg-[#eee25a] px-5 py-3 text-sm font-bold">+ New service request</Link>}</div>
    {error && <p role="alert" className="mt-5 rounded-2xl bg-[#fff0e7] px-4 py-3 text-sm font-bold text-[#934a28]">{error}</p>}
    {mode === "provider" && metrics && <section aria-label="Opportunity performance over the last 90 days" className="mt-6 grid gap-3 sm:grid-cols-3"><Metric label="Matched opportunities" value={String(metrics.opportunities)} /><Metric label="Quotes sent" value={String(metrics.responded)} /><Metric label="Accepted quotes" value={String(metrics.accepted)} /><Metric label="Response rate" value={metrics.responseRate === null ? "Building" : `${metrics.responseRate}%`} note={metrics.responseRate === null ? "Shown after 5 opportunities" : undefined} /><Metric label="Average response" value={metrics.averageResponseMinutes === null ? "Building" : metrics.averageResponseMinutes < 60 ? `${metrics.averageResponseMinutes} min` : `${Math.round(metrics.averageResponseMinutes / 60)} hr`} note={metrics.averageResponseMinutes === null ? "Shown after 3 responses" : undefined} /></section>}
    <div className="mt-7 space-y-5">{items.length ? items.map((item) => <article key={item.id} className="rounded-[2rem] border border-[#183126]/10 bg-white p-5 shadow-sm sm:p-7"><div className="flex flex-col gap-4 sm:flex-row sm:justify-between"><div><div className="flex flex-wrap gap-2"><span className="rounded-full bg-[#e6eee2] px-3 py-1 text-[11px] font-bold">{item.category}</span><span className="rounded-full bg-[#f4f3e7] px-3 py-1 text-[11px] font-bold capitalize">{item.status.replaceAll("_", " ")}</span></div><h2 className="mt-3 text-xl font-bold">{item.title}</h2><p className="mt-2 max-w-3xl text-sm leading-6 text-[#607269]">{item.description}</p></div><div className="shrink-0 text-sm sm:text-right"><p className="font-bold">{new Date(item.preferredStartsAt).toLocaleString("en-US", { month: "short", day: "numeric", hour: "numeric", minute: "2-digit" })}</p><p className="mt-1 text-[#738179]">{item.city}, {item.state} {item.postalCode}</p>{item.distanceMiles != null && <p className="mt-1 text-xs text-[#738179]">{item.distanceMiles.toFixed(1)} mi away</p>}</div></div>
      {mode === "provider" ? <ProviderQuoteForm request={item} busy={busy} setBusy={setBusy} setError={setError} onSent={load} /> : <div className="mt-5 border-t border-[#183126]/10 pt-5"><h3 className="font-bold">{item.quotes.length} {item.quotes.length === 1 ? "quote" : "quotes"}</h3>{item.quotes.length ? <div className="mt-3 grid gap-3">{item.quotes.map((quote) => <div key={quote.id} className="rounded-2xl bg-[#f5f5ef] p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><p className="font-bold">{quote.providerName} · {quote.title}</p><p className="mt-1 text-xs text-[#718078]">{quote.serviceTitle} · Version {quote.version}</p>{quote.description && <p className="mt-2 text-sm leading-6 text-[#607269]">{quote.description}</p>}{quote.notes && <p className="mt-2 text-xs text-[#718078]">Note: {quote.notes}</p>}</div><p className="shrink-0 text-2xl font-bold">${quote.total.toFixed(2)}</p></div>{quote.status === "sent" ? <div className="mt-4 flex flex-col gap-2 sm:flex-row sm:justify-end"><button disabled={busy === quote.id} onClick={() => void respond(quote.id, "decline")} className="min-h-11 rounded-full border border-[#183126]/15 px-5 text-sm font-bold">Decline</button><button disabled={busy === quote.id} onClick={() => void respond(quote.id, "accept")} className="min-h-11 rounded-full bg-[#183126] px-5 text-sm font-bold text-white">Accept quote</button></div> : <p className="mt-3 text-xs font-bold capitalize">{quote.status}</p>}</div>)}</div> : <p className="mt-2 text-sm text-[#718078]">No quotes yet. We will notify you when a provider responds.</p>}{["open", "receiving_responses"].includes(item.status) && <button disabled={busy === item.id} onClick={() => void cancel(item.id)} className="mt-4 text-xs font-bold text-[#92513b] underline">Cancel request</button>}</div>}</article>) : <div className="rounded-[2rem] border border-dashed border-[#183126]/15 bg-white px-6 py-12 text-center"><p className="text-3xl">{mode === "provider" ? "⌁" : "📋"}</p><h2 className="mt-3 font-bold">{mode === "provider" ? "No matching opportunities right now" : "No service requests yet"}</h2><p className="mt-2 text-sm text-[#718078]">{mode === "provider" ? "New requests in your categories and service areas will appear here." : "Send one request and compare responses from local pros."}</p>{mode === "customer" && <Link href="/requests" className="mt-5 inline-flex rounded-full bg-[#183126] px-5 py-3 text-sm font-bold text-white">Request a service</Link>}</div>}</div>
  </div>;
}

function Metric({ label, value, note }: { label: string; value: string; note?: string }) { return <div className="rounded-2xl border border-[#183126]/10 bg-white p-4"><p className="text-xs font-bold uppercase tracking-wider text-[#718078]">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p>{note && <p className="mt-1 text-[11px] text-[#7b8982]">{note}</p>}</div>; }

function ProviderQuoteForm({ request, busy, setBusy, setError, onSent }: { request: JobRequest; busy: string; setBusy: (value: string) => void; setError: (value: string) => void; onSent: () => Promise<void> }) {
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(request.id); setError(""); const form = new FormData(event.currentTarget); const response = await fetch(`/api/job-requests/${request.id}/quotes`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ serviceId: request.matchedServiceId, title: form.get("title"), description: form.get("description"), total: form.get("total"), notes: form.get("notes"), expiresInDays: 7 }) }); const data = await response.json() as { error?: string }; setBusy(""); if (!response.ok) { setError(data.error ?? "The quote could not be sent."); return; } await onSent(); }
  const prior = request.quotes.find((quote) => quote.status === "sent");
  return <form onSubmit={submit} className="mt-5 grid gap-3 rounded-2xl bg-[#f3f5ef] p-4 sm:grid-cols-2"><p className="text-xs font-bold uppercase tracking-wider text-[#65776d] sm:col-span-2">{prior ? "Revise your quote" : `Quote with ${request.matchedServiceTitle ?? "matched service"}`}</p><label className="text-xs font-bold">Quote title<input required name="title" defaultValue={prior?.title ?? request.title} className="mt-1.5 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base" /></label><label className="text-xs font-bold">Total<input required name="total" type="number" min="1" step="0.01" inputMode="decimal" defaultValue={prior?.total} className="mt-1.5 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base" /></label><label className="text-xs font-bold sm:col-span-2">Scope and deliverables<textarea name="description" rows={3} defaultValue={prior?.description} className="mt-1.5 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base" /></label><label className="text-xs font-bold sm:col-span-2">Notes <span className="font-normal">(optional)</span><textarea name="notes" rows={2} defaultValue={prior?.notes} className="mt-1.5 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-base" /></label><button disabled={busy === request.id} className="min-h-11 rounded-full bg-[#183126] px-5 text-sm font-bold text-white sm:col-span-2">{busy === request.id ? "Sending…" : prior ? "Send revised quote" : "Send free quote"}</button></form>;
}
