"use client";

import { FormEvent,useEffect,useState } from "react";
type Recommendation={id:string;displayName:string;relationship:string;body:string;status:string;createdAt:string};

export default function ProviderRecommendationManager(){
  const [email,setEmail]=useState("");const [context,setContext]=useState("");const [items,setItems]=useState<Recommendation[]>([]);const [working,setWorking]=useState(false);const [notice,setNotice]=useState("");const [error,setError]=useState("");
  useEffect(()=>{const controller=new AbortController();fetch("/api/providers/recommendations",{signal:controller.signal,cache:"no-store"}).then(async response=>response.ok?response.json() as Promise<{recommendations:Recommendation[]}>:null).then(data=>{if(data)setItems(data.recommendations);}).catch(()=>null);return()=>controller.abort();},[]);
  async function submit(event:FormEvent){event.preventDefault();setWorking(true);setNotice("");setError("");const response=await fetch("/api/providers/recommendations",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,serviceContext:context})}).catch(()=>null);const data=response?await response.json() as {error?:string}:null;setWorking(false);if(!response?.ok){setError(data?.error??"We could not send the request.");return;}setEmail("");setContext("");setNotice("Recommendation request sent. The one-time link expires in 14 days.");}
  return <section className="mt-8 rounded-[2rem] border border-[#183126]/10 bg-white p-6 shadow-[0_8px_32px_rgba(24,49,38,.06)] sm:p-8"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#718078]">Reputation</p><h2 className="mt-2 text-2xl font-bold">Outside-client recommendations</h2><p className="mt-2 text-sm leading-6 text-[#687a70]">Invite a real past client by email. Submissions are moderated and appear separately from verified BubsBookings reviews.</p><form onSubmit={submit} className="mt-5 grid gap-3 rounded-2xl bg-[#f7f7f2] p-4 sm:grid-cols-[1fr_1fr_auto] sm:items-end"><label className="text-xs font-bold">Client email<input required type="email" value={email} onChange={event=>setEmail(event.target.value)} className="mt-1.5 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-sm outline-none"/></label><label className="text-xs font-bold">Service context <span className="font-normal">(optional)</span><input maxLength={120} value={context} onChange={event=>setContext(event.target.value)} placeholder="Logo design" className="mt-1.5 w-full rounded-xl border border-[#183126]/15 bg-white px-3 py-3 text-sm outline-none"/></label><button disabled={working} className="min-h-11 rounded-full bg-[#eee25a] px-5 text-sm font-bold disabled:opacity-50">{working?"Sending…":"Send request"}</button></form>{notice&&<p role="status" className="mt-3 rounded-xl bg-[#e6f1e5] p-3 text-sm font-bold text-[#34704a]">{notice}</p>}{error&&<p role="alert" className="mt-3 rounded-xl bg-[#fff0e7] p-3 text-sm font-bold text-[#9a4e25]">{error}</p>}<div className="mt-5 grid gap-3 sm:grid-cols-2">{items.map(item=><article key={item.id} className="rounded-2xl border border-[#183126]/10 p-4"><div className="flex items-start justify-between gap-2"><p className="font-bold">{item.displayName}</p><span className="rounded-full bg-[#edf2e9] px-2.5 py-1 text-[10px] font-bold uppercase">{item.status}</span></div><p className="mt-1 text-xs text-[#718078]">{item.relationship}</p><p className="mt-3 text-sm leading-6 text-[#52665b]">{item.body}</p></article>)}</div></section>;
}
