"use client";

import { FormEvent,useState } from "react";

export default function RecommendationForm({token}:{token:string}){
  const [displayName,setDisplayName]=useState("");const [relationship,setRelationship]=useState("");const [recommendation,setRecommendation]=useState("");const [working,setWorking]=useState(false);const [error,setError]=useState("");const [done,setDone]=useState(false);
  async function submit(event:FormEvent){event.preventDefault();setWorking(true);setError("");const response=await fetch("/api/recommendations/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({token,displayName,relationship,recommendation})}).catch(()=>null);const data=response?await response.json() as {error?:string}:null;setWorking(false);if(!response?.ok){setError(data?.error??"We could not submit your recommendation.");return;}setDone(true);}
  if(done)return <div role="status" className="mt-7 rounded-2xl bg-[#e6f1e5] p-6"><h2 className="text-xl font-bold">Thank you</h2><p className="mt-2 text-sm leading-6 text-[#52665b]">Your recommendation was submitted for moderation. This one-time link can no longer be used.</p></div>;
  const input="mt-2 w-full rounded-2xl border border-[#183126]/15 bg-[#fafaf6] px-4 py-3 text-sm outline-none focus:border-[#4d725d]";
  return <form onSubmit={submit} className="mt-7 space-y-5"><label className="block text-sm font-bold">Public display name<input required maxLength={80} autoComplete="name" value={displayName} onChange={event=>setDisplayName(event.target.value)} className={input}/><span className="mt-1.5 block text-xs font-normal text-[#718078]">Use your first name and last initial if you prefer.</span></label><label className="block text-sm font-bold">Relationship or service context<input required minLength={2} maxLength={120} value={relationship} onChange={event=>setRelationship(event.target.value)} className={input} placeholder="Website design client"/></label><label className="block text-sm font-bold">Recommendation<textarea required minLength={20} maxLength={1500} rows={7} value={recommendation} onChange={event=>setRecommendation(event.target.value)} className={`${input} resize-y`} placeholder="What work did the provider do, and what was your experience?"/><span className="mt-1.5 block text-xs font-normal text-[#718078]">{recommendation.length}/1,500</span></label>{error&&<p role="alert" className="rounded-xl bg-[#fff0e7] p-3 text-sm font-bold text-[#9a4e25]">{error}</p>}<button disabled={working} className="min-h-12 rounded-full bg-[#eee25a] px-6 text-sm font-bold disabled:opacity-50">{working?"Submitting…":"Submit recommendation"}</button></form>;
}
