import type { Metadata } from "next";
import { LegalPage } from "@/app/terms/page";

export const metadata: Metadata = { title: "Provider Agreement" };

const sections = [
  ["1. Acceptance and relationship", "This Provider Agreement supplements the Terms of Service. By creating a provider profile, listing a service, or accepting a booking, you accept both agreements for yourself and any business you represent. You provide services as an independent business—not as a BubsBookings employee, agent, franchisee, joint venturer, or representative. You decide how to perform work and are not promised any minimum bookings, territory, or earnings."],
  ["2. Eligibility, licenses, insurance, and workers", "You must be at least 18, authorized to act for the listed business, and legally permitted to provide every offered service. Maintain all registrations, permits, professional or trade licenses, insurance, bonds, training, vehicle coverage, and safety practices required for the work and location. You are responsible for your employees, contractors, helpers, payroll, supervision, workplace safety, background-check obligations, and compliance with employment and tax law. BubsBookings does not employ or pay your workers."],
  ["3. Accurate listings and screening", "Keep your legal identity, contact details, business and service names, locations, working radius, photos, prices, qualifications, availability, and descriptions accurate and current. Use only content you own or may lawfully publish. Starting prices and custom quotes must clearly describe material assumptions and must be accepted before they change a booking price. Automated onboarding checks are not identity, license, insurance, or criminal-background verification and do not transfer your responsibility to BubsBookings."],
  ["4. Service and customer information", "Respond in a reasonable time, honor confirmed appointments, communicate delays or scope changes, and perform safely, professionally, and in accordance with the accepted booking and law. Do not mark a service complete before the agreed work is performed. Use a customer’s address, messages, photos, and contact details only to evaluate or complete that booking, keep them confidential, and do not add the customer to marketing lists without legally sufficient consent."],
  ["5. Stripe Connect and payment authority", <><p>To receive online marketplace payments, complete and maintain a Stripe connected account. Stripe&apos;s <a href="https://stripe.com/legal/connect-account" target="_blank" rel="noreferrer" className="font-bold underline">Connected Account Agreement</a>, including the incorporated Stripe Services Agreement, also applies. You authorize BubsBookings to create and administer charges, refunds, disputes, transfers, reversals, and related Stripe activity as described in these agreements and the product.</p><p className="mt-3">BubsBookings uses separate charges and transfers. The customer charge is made on the BubsBookings platform account; after eligible completion, BubsBookings creates a separate transfer of your share to your connected Stripe account. The delayed amount is not an escrow, trust, or bank account and can remain subject to Stripe availability, reserves, refunds, disputes, and legal restrictions. Stripe controls when money becomes available and when it reaches your bank.</p></>],
  ["6. Fees, plans, and taxes", "BubsBookings deducts the booking-fee percentage shown for your active plan from the customer’s booking amount before transferring your share. Paid plan subscriptions and limits are disclosed at purchase and on the pricing page. An eligible provider company may use one 30-day Pro trial. A card is required, the Pro booking fee applies during the trial, and the plan automatically renews at $9.99 per month unless canceled before the trial ends. Stripe may collect taxpayer information and prepare, file, and deliver an applicable Form 1099 for an eligible U.S. provider when BubsBookings enables Stripe tax reporting and reporting is required. A form is not guaranteed merely because you earned money through the platform. You remain responsible for your business expenses, pricing, sales or service taxes, income and self-employment taxes, filings, records, and any information Stripe or BubsBookings lawfully requests. BubsBookings may withhold or report amounts when legally required."],
  ["7. Completion and payout release", "After performing the service, you may mark it complete. The customer has 48 hours to confirm or open a dispute. If the customer does neither, BubsBookings may confirm automatically and initiate your transfer. Completion does not guarantee immediate bank payout. A transfer will not release while the payment is incomplete, the booking is not eligible, a refund or dispute is open, payout information is incomplete, or an administrator has reasonably frozen it for risk, fraud, correction, or legal review."],
  ["8. Cancellations, refunds, chargebacks, and reversals", "Publish and apply a reasonable, lawful cancellation policy. When a paid booking is canceled before transfer and qualifies under the product rules, BubsBookings may refund it automatically. You authorize BubsBookings to delay, reduce, freeze, offset, or reverse transfers for cancellations, refunds, card disputes, fraud, duplicated or mistaken payments, negative balances, or legal obligations. Because Stripe debits platform-created refunds and chargebacks from the platform, you owe BubsBookings any provider amount attributable to your service that BubsBookings cannot recover through reversal or offset, except where law or a BubsBookings decision places responsibility elsewhere."],
  ["9. Disputes, records, and cooperation", "Keep accurate service, quote, scheduling, completion, cancellation, and customer-communication records. Respond promptly and truthfully to requests for evidence. BubsBookings may consider messages, booking events, photos, payment records, reports, and other relevant information, but does not promise to resolve every factual disagreement. Do not retaliate against a customer for a good-faith complaint, report, review, or legal right."],
  ["10. Prohibited provider conduct", "Do not misrepresent credentials or reviews; list illegal, unsafe, discriminatory, sexually exploitative, or deceptive services; substitute an undisclosed person when identity matters; demand gift cards, cryptocurrency, authentication codes, or unnecessary sensitive data; manipulate availability or completion; evade platform fees; or use customer information for an unrelated purpose. You must make legally required accessibility accommodations and may not unlawfully discriminate."],
  ["11. Suspension and termination", "BubsBookings may pause or remove listings, payment access, transfers, or accounts when reasonably needed to protect users, investigate reports, enforce agreements, correct payments, comply with Stripe or law, or address risk. You may stop listing services, but outstanding bookings, refunds, disputes, taxes, reversals, record duties, and amounts owed survive. Termination does not require BubsBookings to delete records it lawfully must or may retain."],
  ["12. Provider responsibility", "You are responsible for claims, losses, fines, taxes, injuries, property damage, and reasonable costs arising from your services, workers, listings, legal noncompliance, misuse of customer information, or breach of this agreement, except to the extent caused by BubsBookings or prohibited by law. You agree to cooperate in defending covered third-party claims. The Terms’ disclaimers, liability limits, governing-law provision, and support process also apply."],
] as const;

export default function ProviderAgreementPage() {
  return <LegalPage eyebrow="For service professionals" title="Provider Agreement" intro="The marketplace, payment, and service standards that apply when you offer work through BubsBookings." sections={sections} />;
}
