import BrandLockup from "@/components/brand-lockup";
import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Terms of Service", alternates: { canonical: "/terms" } };

const sections = [
  ["1. Agreement, eligibility, and authority", <><p>By creating an account, clicking an acceptance box, or using BubsBookings, you agree to these Terms and acknowledge the Privacy Policy and AI &amp; Safety disclosure. You must be at least 18, legally able to enter a binding agreement, and—if acting for a business—authorized to bind it.</p><p className="mt-3">Providers also agree to the Provider Agreement when they create a provider profile or list a service. If you do not agree, do not use the service.</p></>],
  ["2. Accounts and electronic communications", "Provide accurate, current information; use your own account; protect your password and authentication codes; and promptly report unauthorized access. You are responsible for activity under your account except to the extent caused by BubsBookings. You agree to receive account, booking, safety, legal, and payment notices electronically. Marketing messages, if offered, require any consent required by law and can be unsubscribed from separately."],
  ["3. Marketplace role", "BubsBookings is an online marketplace that helps customers discover, book, pay, and communicate with independent providers. BubsBookings does not perform the listed services and is not the employer, agent, partner, or insurer of a provider. Providers decide how to perform their work and remain responsible for their identity, qualifications, pricing, availability, workers, and results. Automated screening or an account badge is not a background check, license verification, endorsement, or guarantee."],
  ["4. Listings, quotes, and bookings", "Listings, photos, availability, starting prices, and custom quotes must be accurate and lawful. A booking request is not confirmed until the provider accepts it, and a changed quote is not binding until the customer accepts it. The parties must review the final scope, location, timing, price, cancellation terms, and any special requirements before service. BubsBookings is currently intended for services and users in the United States. Do not use BubsBookings for emergency, medical or health-care, regulated financial, legal, or other services the provider is not legally qualified to perform."],
  ["5. Payments, plans, and fees", <><p>Stripe processes online payments and connected-provider payouts under Stripe’s terms. BubsBookings uses separate charges and transfers: the customer’s charge is created on the BubsBookings Stripe platform account, and the provider transfer is created later. This is a delayed marketplace transfer—not an escrow account, trust account, deposit account, or bank service—and funds can be subject to Stripe availability, reserves, refunds, disputes, and legal restrictions.</p><p className="mt-3">When a customer pays for a confirmed booking, a $2.99 BubsBookings service fee is added at checkout and shown separately before payment. Requesting a booking does not create this charge. The provider receives the service price less the booking fee for the provider’s active plan; the customer service fee does not reduce the provider’s listed service price or payout calculation.</p><p className="mt-3">Published subscription prices, plan limits, booking fees, taxes, and Stripe processing consequences may apply. An eligible provider company may receive one 30-day Pro trial and must provide a payment method at signup. The trial includes Pro features and the Pro booking fee. Unless canceled before it ends, the trial automatically becomes a $9.99 monthly subscription charged to the saved payment method. Paid plans renew at the disclosed billing interval until canceled; cancellation stops future renewal and does not ordinarily refund a period already started unless required by law or stated at purchase.</p></>],
  ["6. Completion, cancellation, refunds, and payment disputes", <><p>A provider may mark a service complete only after performing it. The customer then has 48 hours to confirm completion or open a dispute. If the customer does neither, BubsBookings may automatically treat the service as complete and release the provider transfer.</p><p className="mt-3">When an eligible paid booking is canceled before transfer, BubsBookings may automatically refund the payment. Late cancellations, partial performance, completed work, custom refund requests, suspected fraud, and payments already transferred require review. An approved refund is sent to the original payment method; Stripe and the customer’s bank control final timing. If money was already transferred, BubsBookings may reverse or offset the transfer. A bank chargeback is governed by the card network and Stripe and may result in account restrictions while reviewed.</p></>],
  ["7. User conduct and safety", "Do not post or send unlawful, hateful, sexually explicit, threatening, exploitative, harassing, deceptive, or abusive content; arrange illegal activity; impersonate anyone; manipulate reviews; bypass fees or safety controls; scrape the service; introduce malware; or misuse personal information. Never include passwords, full card numbers, government identifiers, or unnecessary health information in messages or booking notes. For immediate danger, contact emergency services—not BubsBookings."],
  ["8. Automated checks and reports", "BubsBookings uses automated rules to screen certain submitted text and provider-profile information. The system may block content or prevent publication and create a limited safety record. It does not perform criminal background checks, determine whether a service is safe, or replace human judgment. Users may report accounts, listings, bookings, messages, disputes, and bugs; knowingly false or abusive reports are prohibited. See AI & Safety for details and limits."],
  ["9. Reviews and user content", <>Reviews must reflect a genuine experience and may not be purchased, coerced, fabricated, or used to make unlawful threats. You keep ownership of content you submit and confirm you have the rights and permissions needed to submit it. You grant BubsBookings a worldwide, non-exclusive, royalty-free license to host, store, reproduce, format, display, and distribute that content only as reasonably needed to operate, secure, improve, and promote BubsBookings. You may delete content where the product allows, but transaction, safety, backup, or legal records may remain. Do not upload intimate imagery, content that violates another person&apos;s privacy or publicity rights, or content you do not have permission to use. See <Link href="/content-removal" className="font-bold underline">Content Removal</Link> to report unlawful, infringing, or nonconsensual intimate content, including without an account.</>],
  ["10. Suspension, account deletion, and termination", <>You may stop using BubsBookings at any time, download your account data, or request permanent deletion through Account Settings, subject to resolving active bookings, disputes, and unsettled payments. Account deletion is irreversible and may cancel provider subscriptions and remove public listings. Limited payment, tax, fraud-prevention, backup, or legal records may remain as described in the <Link href="/privacy" className="font-bold underline">Privacy Policy</Link>. BubsBookings may remove content, pause a listing or payout, limit features, or suspend or terminate an account when reasonably needed to enforce these Terms, protect users, address fraud or payment risk, comply with law, or protect the service. Provisions that by their nature should survive—including payment, dispute, disclaimer, and liability terms—continue after termination.</>],
  ["11. Third-party services", "BubsBookings depends on third parties such as Stripe for payments, Google for optional sign-in, and hosting, storage, email, and security providers. Their separate terms and privacy policies govern their services. BubsBookings is not responsible for a third party’s independent acts, outages, or eligibility decisions, but this does not limit rights that cannot legally be waived."],
  ["12. Disclaimers and limits", "To the fullest extent permitted by law, BubsBookings and its content are provided “as is” and “as available,” without implied guarantees of uninterrupted availability or of a provider’s identity, safety, legality, quality, or results. BubsBookings is not liable for indirect, incidental, special, exemplary, or consequential damages arising from marketplace use. Nothing in these Terms excludes liability or consumer rights that applicable law does not allow us to exclude."],
  ["13. Governing law and resolving issues", "First contact BubsBookings support with a clear description and relevant booking information. These Terms are governed by Washington law, without regard to conflict-of-law rules, except where mandatory consumer law requires otherwise. Any court proceeding must be brought in a court with jurisdiction in Washington, unless applicable law gives you the right to proceed elsewhere. These Terms do not require private arbitration or waive a lawful right to participate in a class action."],
  ["14. Changes, severability, and contact", <>If a provision is unenforceable, the remaining provisions continue. Failure to enforce a provision is not a waiver. BubsBookings may update these Terms as the service or law changes; material changes will be presented in the service or by another appropriate notice and, when required, will take effect only after new consent. Questions or legal notices may be submitted through Contact Support or by email to <a href="mailto:christian@bubsbookings.com" className="font-bold underline">christian@bubsbookings.com</a>. Email is not monitored for emergencies.</>],
] as const;

export default function TermsPage() {
  return <LegalPage eyebrow="Legal" title="Terms of Service" intro="The rules that keep BubsBookings useful, fair, and safe for customers and providers." sections={sections} />;
}

export function LegalPage({ eyebrow, title, intro, sections, effectiveDate = "September 13, 2026" }: { eyebrow: string; title: string; intro: string; sections: ReadonlyArray<readonly [string, string | React.ReactNode]>; effectiveDate?: string }) {
  const sectionLinks = sections.map(([heading]) => ({ heading, id: `section-${heading.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "")}` }));
  return <main className="legal-page min-h-screen bg-[#f8f7f3] text-[#183126]">
    <header className="border-b border-[#183126]/10 bg-[#f8f7f3]/90"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3 px-5 py-4 sm:px-6"><Link href="/" aria-label="BubsBookings home"><BrandLockup /></Link><div className="flex items-center gap-1"><Link href="/guides" className="site-nav-link hidden sm:inline-flex">Guides</Link><Link href="/" className="site-nav-link">Back home</Link></div></div></header>
    <article className="mx-auto max-w-6xl px-5 py-12 sm:px-6 sm:py-20">
      <div className="legal-hero relative overflow-hidden rounded-[2.25rem] border border-[#183126]/10 bg-[#173d2e] p-7 text-white shadow-[0_28px_80px_rgba(19,46,35,.17)] sm:p-12">
        <div aria-hidden="true" className="absolute -right-16 -top-24 h-72 w-72 rounded-full bg-[#eee25a]/15 blur-3xl" />
        <div className="relative"><p className="text-xs font-bold uppercase tracking-[.18em] text-[#bfd2c7]">{eyebrow}</p><h1 className="mt-3 max-w-3xl text-4xl font-bold tracking-[-.05em] sm:text-6xl">{title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#d4e1da]">{intro}</p><div className="mt-6 inline-flex rounded-full border border-white/15 bg-white/10 px-4 py-2 text-xs font-bold">Effective {effectiveDate}</div></div>
      </div>
      <div className="mt-8 grid items-start gap-8 lg:grid-cols-[15rem_minmax(0,1fr)]">
        <aside className="legal-toc rounded-[1.5rem] border border-[#183126]/10 bg-white p-5 lg:sticky lg:top-24"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#718078]">On this page</p><nav aria-label={`${title} sections`} className="mt-4 grid gap-1">{sectionLinks.map(({ heading, id }) => <a key={id} href={`#${id}`} className="rounded-xl px-3 py-2 text-sm font-semibold leading-5 text-[#5f7167] hover:bg-[#edf3e9] hover:text-[#183126]">{heading}</a>)}</nav></aside>
        <div className="space-y-5">{sections.map(([heading, content], index) => <section id={sectionLinks[index].id} key={heading} className="legal-section scroll-mt-28 rounded-[1.75rem] border border-[#183126]/10 bg-white p-6 sm:p-8"><h2 className="text-xl font-bold sm:text-2xl">{heading}</h2><div className="mt-4 text-[15px] leading-7 text-[#566a5f]">{content}</div></section>)}</div>
      </div>
      <nav aria-label="Legal policies" className="mt-10 flex flex-wrap gap-3"><Link href="/terms" className="rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold transition hover:bg-[#e5eddf]">Terms</Link><Link href="/privacy" className="rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold transition hover:bg-[#e5eddf]">Privacy</Link><Link href="/provider-agreement" className="rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold transition hover:bg-[#e5eddf]">Provider Agreement</Link><Link href="/ai-transparency" className="rounded-full bg-[#183126] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#315846]">AI &amp; Safety</Link><Link href="/cookies" className="rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold transition hover:bg-[#e5eddf]">Cookies</Link><Link href="/content-removal" className="rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold transition hover:bg-[#e5eddf]">Content Removal</Link><Link href="/accessibility" className="rounded-full border border-[#183126]/15 bg-white px-5 py-3 text-sm font-bold transition hover:bg-[#e5eddf]">Accessibility</Link></nav>
      <p className="mt-8 text-xs leading-5 text-[#7b8982]">This is BubsBookings&apos; operational policy, not legal advice. A qualified attorney should review it before live payments launch and whenever BubsBookings enters a new jurisdiction or materially changes its marketplace or payment model.</p>
    </article>
  </main>;
}
