import { NextResponse } from "next/server";
import { database } from "@/lib/database";
import { enforceRateLimit,recordActivity } from "@/lib/request-security";
import { cleanText,getMarketingAccess,isMarketingConfigured,listProviderClients,renderCampaignEmail,sendMarketingEmail,type CampaignContent,type ClientFilters,validMarketingEmail,emailHash } from "@/lib/provider-marketing";

const templates:Record<string,CampaignContent>={thank_you:{title:"Thank you, {{first_name}}",body:"We appreciate your business and hope you loved {{last_service}}. When you are ready, we would be happy to help again.",buttonText:"Book again",buttonUrl:"",color:"#183126"},book_again:{title:"Ready to book again?",body:"Hi {{first_name}}, it may be time for your next service with {{business_name}}. Review current availability and pricing below.",buttonText:"View availability",buttonUrl:"",color:"#34704a"},seasonal:{title:"A seasonal update from {{business_name}}",body:"Hi {{first_name}}, we are opening availability for the season. We would love to work with you again.",buttonText:"View services",buttonUrl:"",color:"#6f7f42"},appreciation:{title:"We appreciate you",body:"Thank you for choosing {{business_name}}. Your support means a great deal to our local business.",buttonText:"Visit our profile",buttonUrl:"",color:"#183126"},announcement:{title:"News from {{business_name}}",body:"Hi {{first_name}}, we wanted to share an update with our previous customers.",buttonText:"Learn more",buttonUrl:"",color:"#183126"}};
function parseFilters(value:unknown):ClientFilters{if(!value||typeof value!=="object"||Array.isArray(value))return {};const raw=value as Record<string,unknown>;return {search:cleanText(raw.search,100)||undefined,tagId:cleanText(raw.tagId,50)||undefined,serviceId:cleanText(raw.serviceId,50)||undefined,category:cleanText(raw.category,80)||undefined,bookingState:["repeat","one_time","upcoming","inactive"].includes(String(raw.bookingState))?raw.bookingState as ClientFilters["bookingState"]:undefined,marketing:["subscribed","unsubscribed","never_emailed"].includes(String(raw.marketing))?raw.marketing as ClientFilters["marketing"]:undefined,minSpent:Number(raw.minSpent)||undefined,minBookings:Number(raw.minBookings)||undefined,lastBookingDays:Number(raw.lastBookingDays)||undefined};}
function content(value:unknown,key:string):CampaignContent{const base=templates[key]??templates.announcement;const raw=value&&typeof value==="object"&&!Array.isArray(value)?value as Record<string,unknown>:{};return {title:cleanText(raw.title,120)||base.title,body:cleanText(raw.body,4000)||base.body,buttonText:cleanText(raw.buttonText,50)||base.buttonText,buttonUrl:cleanText(raw.buttonUrl,500),color:/^#[0-9a-f]{6}$/i.test(String(raw.color))?String(raw.color):base.color};}
async function providerInfo(id:string){return database.query<{business_name:string;plan:string;user_id:string;email:string;status:string}>(`SELECT p.business_name,p.plan,p.user_id,u.email,COALESCE(a.status,'enabled') status FROM provider_profiles p JOIN "user" u ON u.id=p.user_id LEFT JOIN provider_marketing_access a ON a.provider_id=p.id WHERE p.id::text=$1`,[id]).then(r=>r.rows[0]);}

export async function GET(){const access=await getMarketingAccess("view");if(!access)return NextResponse.json({error:"Campaign access is not available."},{status:403});const [campaigns,tags,services,provider]=await Promise.all([database.query(`SELECT c.id::text,c.name,c.subject,c.preview_text,c.template_key,c.content,c.audience_definition,c.status,c.scheduled_at,c.sent_at,c.recipient_count,c.created_at,count(r.id) FILTER(WHERE r.status IN('sent','delivered'))::int sent_count,count(r.id) FILTER(WHERE r.status='delivered')::int delivered_count,count(r.id) FILTER(WHERE r.status IN('hard_bounced','soft_bounced'))::int bounce_count,count(r.id) FILTER(WHERE r.status='complained')::int complaint_count,count(r.id) FILTER(WHERE r.status='unsubscribed')::int unsubscribe_count,count(DISTINCT e.recipient_id) FILTER(WHERE e.event_type='click')::int unique_clicks,count(DISTINCT a.booking_id)::int booking_count,COALESCE(sum(b.price_cents) FILTER(WHERE a.booking_id IS NOT NULL),0)::bigint attributed_cents FROM marketing_campaigns c LEFT JOIN marketing_campaign_recipients r ON r.campaign_id=c.id LEFT JOIN marketing_email_events e ON e.recipient_id=r.id LEFT JOIN marketing_attributions a ON a.recipient_id=r.id LEFT JOIN bookings b ON b.id=a.booking_id WHERE c.provider_id::text=$1 GROUP BY c.id ORDER BY c.created_at DESC LIMIT 100`,[access.providerId]),database.query(`SELECT id::text,name,color FROM provider_client_tags WHERE provider_id::text=$1 ORDER BY name`,[access.providerId]),database.query(`SELECT id::text,title,category FROM services WHERE provider_id::text=$1 AND is_active=true ORDER BY title`,[access.providerId]),providerInfo(access.providerId)]);return NextResponse.json({campaigns:campaigns.rows,tags:tags.rows,services:services.rows,marketingConfigured:isMarketingConfigured(),marketingStatus:provider?.status??"disabled",templates:Object.entries(templates).map(([key,value])=>({key,...value}))});}

export async function POST(request:Request){
  const access=await getMarketingAccess("manage");if(!access)return NextResponse.json({error:"You do not have permission to create campaigns."},{status:403});if(!await enforceRateLimit({request,userId:access.session.user.id,bucket:"provider-campaign-change",limit:30}))return NextResponse.json({error:"Too many campaign changes. Please wait."},{status:429});
  const body=await request.json().catch(()=>null) as Record<string,unknown>|null;if(!body)return NextResponse.json({error:"Enter valid campaign details."},{status:400});
  const name=cleanText(body.name,100),subject=cleanText(body.subject,150),preview=cleanText(body.previewText,180),templateKey=templates[String(body.templateKey)]?String(body.templateKey):"announcement",audience=parseFilters(body.audience),safeContent=content(body.content,templateKey);
  if(!name||!subject)return NextResponse.json({error:"Campaign name and subject are required."},{status:400});
  const created=await database.query<{id:string}>(`INSERT INTO marketing_campaigns(provider_id,created_by,name,subject,preview_text,template_key,content,audience_definition) VALUES($1,$2,$3,$4,$5,$6,$7::jsonb,$8::jsonb) RETURNING id::text`,[access.providerId,access.session.user.id,name,subject,preview,templateKey,JSON.stringify(safeContent),JSON.stringify(audience)]);await recordActivity({userId:access.session.user.id,action:"marketing_campaign_created",targetType:"campaign",targetId:created.rows[0].id});return NextResponse.json({id:created.rows[0].id},{status:201});
}

export async function PATCH(request:Request){
  const body=await request.json().catch(()=>null) as Record<string,unknown>|null;const action=String(body?.action||"");const access=await getMarketingAccess(action==="schedule"||action==="send_test"?"send":"manage");if(!access)return NextResponse.json({error:"You do not have permission for that campaign action."},{status:403});if(!await enforceRateLimit({request,userId:access.session.user.id,bucket:"provider-campaign-action",limit:20}))return NextResponse.json({error:"Too many campaign actions. Please wait."},{status:429});
  const campaignId=typeof body?.campaignId==="string"?body.campaignId:"";const campaign=await database.query<{id:string;name:string;subject:string;template_key:string;content:CampaignContent;audience_definition:ClientFilters;status:string}>(`SELECT id::text,name,subject,template_key,content,audience_definition,status FROM marketing_campaigns WHERE id::text=$1 AND provider_id::text=$2`,[campaignId,access.providerId]).then(r=>r.rows[0]);if(!campaign)return NextResponse.json({error:"Campaign not found."},{status:404});
  if(action==="cancel"){if(!["draft","scheduled","sending","paused"].includes(campaign.status))return NextResponse.json({error:"This campaign can no longer be cancelled."},{status:409});await database.query(`UPDATE marketing_campaigns SET status='cancelled',cancelled_at=now() WHERE id::text=$1 AND provider_id::text=$2`,[campaignId,access.providerId]);await database.query(`UPDATE marketing_campaign_recipients SET status='cancelled' WHERE campaign_id::text=$1 AND provider_id::text=$2 AND status='queued'`,[campaignId,access.providerId]);return NextResponse.json({ok:true});}
  if(action==="audience_preview"){
    const clients=await listProviderClients(access.providerId,campaign.audience_definition,5000,0);const rows=clients.rows as Array<Record<string,unknown>>;const hashes=rows.map(row=>emailHash(String(row.email||"")));const suppressed=hashes.length?await database.query<{email_hash:string}>(`SELECT DISTINCT email_hash FROM marketing_suppressions WHERE email_hash=ANY($1::text[]) AND (provider_id IS NULL OR provider_id::text=$2)`,[hashes,access.providerId]):{rows:[]};const blocked=new Set(suppressed.rows.map(row=>row.email_hash));const seen=new Set<string>();let unsubscribed=0,invalid=0,duplicates=0,suppressedCount=0,eligible=0;for(const row of rows){const email=String(row.email||"").toLowerCase();if(row.marketing_status==="unsubscribed"){unsubscribed++;continue;}if(!validMarketingEmail(email)){invalid++;continue;}if(seen.has(email)){duplicates++;continue;}seen.add(email);if(blocked.has(emailHash(email))){suppressedCount++;continue;}eligible++;}return NextResponse.json({audience:{total:rows.length,eligible,unsubscribed,invalid,duplicates,suppressed:suppressedCount}});
  }
  const provider=await providerInfo(access.providerId);if(!provider||provider.status!=="enabled")return NextResponse.json({error:"Marketing sending is not enabled for this provider."},{status:403});
  if(action==="send_test"){
    const rendered=renderCampaignEmail({content:campaign.content,subject:`[TEST] ${campaign.subject}`,businessName:provider.business_name,recipient:{id:"test",providerId:access.providerId,campaignId,firstName:access.session.user.name?.split(" ")[0]||"there",lastService:"sample service",lastBookingDate:new Date().toLocaleDateString(),serviceSlug:""}});const sent=await sendMarketingEmail({to:access.session.user.email,fromName:provider.business_name,subject:rendered.subject,html:rendered.html.replace("CLICK_URL",rendered.clickUrl),unsubscribeUrl:rendered.unsubscribeUrl,idempotencyKey:`test-${campaignId}-${Date.now()}`});return sent.sent?NextResponse.json({ok:true}):NextResponse.json({error:sent.error},{status:503});
  }
  if(action==="schedule"){
    if(!isMarketingConfigured())return NextResponse.json({error:"Marketing email infrastructure must be configured before scheduling."},{status:503});if(campaign.status!=="draft")return NextResponse.json({error:"Only draft campaigns can be scheduled."},{status:409});
    const clients=await listProviderClients(access.providerId,{...campaign.audience_definition,marketing:"subscribed"},5000,0);let eligible=0;const db=await database.connect();try{await db.query("BEGIN");for(const row of clients.rows as Array<Record<string,unknown>>){const email=String(row.email||"").toLowerCase();if(!validMarketingEmail(email))continue;const suppressed=await db.query(`SELECT 1 FROM marketing_suppressions WHERE email_hash=$1 AND (provider_id IS NULL OR provider_id::text=$2) LIMIT 1`,[emailHash(email),access.providerId]);if(suppressed.rows[0])continue;await db.query(`INSERT INTO marketing_campaign_recipients(campaign_id,provider_id,customer_id,email,display_name,personalization) VALUES($1,$2,$3,$4,$5,$6::jsonb) ON CONFLICT DO NOTHING`,[campaignId,access.providerId,row.customer_id,email,row.display_name,JSON.stringify({firstName:String(row.display_name||"").split(" ")[0],lastService:row.last_service,lastBookingDate:row.last_booking_at,serviceSlug:row.last_service_slug})]);eligible++;}const scheduledAt=body?.scheduledAt?new Date(String(body.scheduledAt)):new Date();if(Number.isNaN(scheduledAt.getTime())||scheduledAt.getTime()>Date.now()+365*86400000)throw new Error("invalid schedule");await db.query(`UPDATE marketing_campaigns SET status='scheduled',scheduled_at=$3,recipient_count=(SELECT count(*) FROM marketing_campaign_recipients WHERE campaign_id::text=$1) WHERE id::text=$1 AND provider_id::text=$2`,[campaignId,access.providerId,scheduledAt]);await db.query("COMMIT");return NextResponse.json({ok:true,eligible});}catch(error){await db.query("ROLLBACK");return NextResponse.json({error:error instanceof Error&&error.message==="invalid schedule"?"Choose a valid send time within the next year.":"The audience could not be scheduled."},{status:400});}finally{db.release();}
  }
  return NextResponse.json({error:"Unsupported campaign action."},{status:400});
}
