import type { Metadata } from "next";
import Link from "next/link";
import { GUIDES } from "@/lib/guides";

export const metadata: Metadata = {
  title: "BubsBookings Blog",
  description: "Practical BubsBookings articles for comparing, hiring, and working with local service providers.",
  alternates: { canonical: "/guides" },
};

export default async function GuidesPage({ searchParams }: PageProps<"/guides">) {
  const requestedAudience = (await searchParams).audience;
  const audienceValue = Array.isArray(requestedAudience) ? requestedAudience[0] : requestedAudience;
  const audience = audienceValue === "customers" || audienceValue === "providers" ? audienceValue : "all";
  const customerGuides = GUIDES.filter((guide) => guide.category !== "Provider growth");
  const providerGuides = GUIDES.filter((guide) => guide.category === "Provider growth");
  const visibleGuides = audience === "providers" ? providerGuides : audience === "customers" ? customerGuides : GUIDES;
  const filterClass = (active: boolean) => `rounded-full border px-4 py-2 text-xs font-bold transition focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#183126] focus-visible:ring-offset-2 ${active ? "border-[#183126] bg-[#183126] text-white" : "border-[#183126]/10 bg-white hover:border-[#70877a] hover:bg-[#e9f0e5]"}`;

  return <main className="min-h-screen bg-[#f8f7f3] text-[#183126]"><header className="border-b border-[#183126]/10 bg-white"><div className="mx-auto flex max-w-6xl items-center justify-between px-5 py-4 sm:px-8"><Link href="/" className="flex items-center gap-2.5 text-xl font-bold"><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#183126] text-[#eee25a]">B</span>BubsBookings</Link><Link href="/services" className="rounded-full px-4 py-2 text-sm font-bold hover:bg-[#eee25a]">Explore services</Link></div></header><section className="mx-auto max-w-6xl px-5 py-12 sm:px-8 sm:py-16"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#687b70]">BubsBookings Blog</p><h1 className="mt-3 max-w-3xl text-4xl font-bold tracking-[-.05em] sm:text-6xl">Better bookings for customers and providers.</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-[#5d7066]">Practical articles for hiring local help, growing a service business, preparing for appointments, and avoiding surprises.</p><nav aria-label="Filter blog articles" className="mt-8 flex flex-wrap gap-2"><Link href="/guides" aria-current={audience === "all" ? "page" : undefined} className={filterClass(audience === "all")}>All articles · {GUIDES.length}</Link><Link href="/guides?audience=customers" aria-current={audience === "customers" ? "page" : undefined} className={filterClass(audience === "customers")}>For customers · {customerGuides.length}</Link><Link href="/guides?audience=providers" aria-current={audience === "providers" ? "page" : undefined} className={filterClass(audience === "providers")}>For providers · {providerGuides.length}</Link></nav><p aria-live="polite" className="mt-5 text-sm font-semibold text-[#687b70]">Showing {visibleGuides.length} {visibleGuides.length === 1 ? "article" : "articles"}</p><div className="mt-4 grid gap-5 md:grid-cols-2">{visibleGuides.map((guide) => { const isNew = guide.publishedAt === "2026-09-15"; return <article key={guide.slug} className={`relative rounded-[2rem] border bg-white p-6 shadow-[0_8px_25px_rgba(24,49,38,.05)] sm:p-8 ${isNew ? "border-[#d6c94e]" : "border-[#183126]/10"}`}>{isNew && <span className="absolute right-6 top-6 rounded-full bg-[#eee25a] px-3 py-1 text-[10px] font-bold uppercase tracking-[.1em]">New</span>}<p className="pr-14 text-xs font-bold uppercase tracking-[.14em] text-[#718078]">{guide.category} · {guide.readMinutes} min read</p><h2 className="mt-3 text-2xl font-bold tracking-tight">{guide.title}</h2><p className="mt-3 text-sm leading-6 text-[#64766c]">{guide.description}</p><p className="mt-4 text-xs font-semibold text-[#7a8981]">Published {new Date(`${guide.publishedAt}T12:00:00Z`).toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric", timeZone: "UTC" })}</p><Link href={`/guides/${guide.slug}`} className="mt-6 inline-flex rounded-full bg-[#183126] px-5 py-3 text-sm font-bold text-white transition hover:bg-[#315846]">Read article →</Link></article>; })}</div></section></main>;
}
