import type { Metadata } from "next";
import { LegalPage } from "@/app/terms/page";

export const metadata: Metadata = { title: "Content Removal", alternates: { canonical: "/content-removal" } };

const sections = [
  ["1. Report content—no account required", <>Anyone may request review of content on BubsBookings that is unlawful, infringes intellectual-property or privacy rights, or depicts an intimate image shared without consent. Email <a href="mailto:christian@bubsbookings.com?subject=BubsBookings%20content%20removal%20request" className="font-bold underline">christian@bubsbookings.com</a> with “Content removal request” in the subject. An account is not required. This channel is for removal requests, not emergencies; call 911 or the appropriate emergency service if someone is in immediate danger. Do not send passwords, full payment-card details, or unnecessary identity documents.</>],
  ["2. Urgent intimate-image removal", <><p>For an intimate photo, video, or digital forgery—including an AI-generated or altered image—identify the exact BubsBookings location and state that you are the identifiable person depicted or their authorized representative and have a good-faith belief the depiction was published without consent. Include your name or typed signature and a reliable way to contact you. Do not attach or retransmit the intimate image when a URL or content location is enough to identify it.</p><p className="mt-3">BubsBookings will acknowledge a complete request with a reference that can be used for status questions. For a valid request covered by the federal TAKE IT DOWN Act, BubsBookings will remove the reported depiction and make reasonable efforts to identify and remove known identical copies as soon as possible and no later than 48 hours after receiving the complete request. BubsBookings will confirm the action or explain what additional information is needed. The Federal Trade Commission provides reporting and support information at <a href="https://www.takeitdown.ftc.gov/" target="_blank" rel="noreferrer" className="font-bold underline">TakeItDown.ftc.gov</a>.</p></>],
  ["3. What to include for other requests", "Identify the exact BubsBookings URL, listing, message, image, account, or other location; describe the content and the right or rule involved; provide your name and a reliable contact method; explain your relationship to the affected person or rights owner; and include a good-faith statement that the report is accurate. A typed full name may serve as your signature. If the content is already visible at a BubsBookings URL, do not attach or retransmit sensitive material unless BubsBookings specifically and securely requests it."],
  ["4. Copyright and other intellectual property", <><p>For a copyright complaint, identify the copyrighted work, the material claimed to infringe it, and information reasonably sufficient to locate both; provide contact information and a physical or electronic signature; state your good-faith belief that the disputed use is not authorized by the owner, its agent, or law; and state under penalty of perjury that the notice is accurate and that you are the owner or authorized to act for the owner. For a trademark complaint, identify the mark, registration if applicable, challenged use, location, and why you believe the use is unauthorized or misleading.</p><p className="mt-3">BubsBookings may request missing information, notify the person who posted the material, remove or restrict the content, or decline an incomplete or unsupported request. A person whose content was removed may ask for the reason and submit a response or, for an eligible copyright removal, a legally sufficient counter-notice. The U.S. Copyright Office explains the federal notice-and-takedown process and counter-notice requirements in its <a href="https://www.copyright.gov/512/" target="_blank" rel="noreferrer" className="font-bold underline">Section 512 resources</a>.</p></>],
  ["5. Review, records, and misuse", "BubsBookings may preserve limited information about a report, the affected content, and the action taken for safety, evidence preservation, repeat-abuse prevention, legal compliance, and dispute handling. Reports are handled as confidentially as practical but may be disclosed to the person who posted the content, service providers, advisers, or authorities when necessary and lawful. Knowingly false, fraudulent, or abusive reports may lead to rejection, account action, or legal consequences. Nothing on this page limits a right or remedy available under applicable law."],
] as const;

export default function ContentRemovalPage() {
  return <LegalPage eyebrow="Safety and rights" title="Content Removal" intro="A public, no-account-required process for reporting unlawful, infringing, privacy-invasive, or nonconsensual intimate content." sections={sections} />;
}
